/**
 * Core vocabulary data - Easy to maintain and extend
 * Each entry defines a word/phrase with common wrong answers
 */

// Pronouns
export const pronouns = {
  je: {
    french: "je",
    english: "I",
    englishFull: "I", // no ambiguity
    type: "singular",
    person: "first",
  },
  tu: {
    french: "tu",
    english: "you (informal)",
    englishFull: "you (informal - friends/family)",
    type: "singular",
    person: "second",
    note: "Use with friends/family",
  },
  il: {
    french: "il",
    english: "he",
    englishFull: "he", // no ambiguity
    type: "singular",
    person: "third",
    gender: "masculine",
  },
  elle: {
    french: "elle",
    english: "she",
    englishFull: "she", // no ambiguity
    type: "singular",
    person: "third",
    gender: "feminine",
  },
  nous: {
    french: "nous",
    english: "we",
    englishFull: "we", // no ambiguity
    type: "plural",
    person: "first",
  },
  vous: {
    french: "vous",
    english: "you (formal/plural)",
    englishFull: "you (formal or plural - strangers/groups)",
    type: "plural",
    person: "second",
    note: "Use with strangers/bosses",
  },
  ils: {
    french: "ils",
    english: "they (masculine)",
    englishFull: "they (masculine or mixed group)",
    type: "plural",
    person: "third",
    gender: "masculine",
    note: "masculine or mixed group",
  },
  elles: {
    french: "elles",
    english: "they (feminine)",
    englishFull: "they (all feminine group)",
    type: "plural",
    person: "third",
    gender: "feminine",
    note: "all feminine group",
  },
  on: {
    french: "on",
    english: "we / one / people",
    englishFull: "we (informal) / one (impersonal) / people (general)",
    type: "singular",
    person: "third",
    note: "⭐ Uses il/elle verb forms! More common than 'nous'!",
  },
};

// Verb être (to be) conjugations
export const etreConjugations = {
  je: {
    pronoun: "je",
    conjugation: "suis",
    combined: "je suis",
    english: "I am",
    englishFull: "I am", // no ambiguity
  },
  tu: {
    pronoun: "tu",
    conjugation: "es",
    combined: "tu es",
    english: "you are (informal)",
    englishFull: "you are (informal)",
  },
  il: {
    pronoun: "il",
    conjugation: "est",
    combined: "il est",
    english: "he is",
    englishFull: "he is", // no ambiguity
  },
  elle: {
    pronoun: "elle",
    conjugation: "est",
    combined: "elle est",
    english: "she is",
    englishFull: "she is", // no ambiguity
  },
  nous: {
    pronoun: "nous",
    conjugation: "sommes",
    combined: "nous sommes",
    english: "we are",
    englishFull: "we are", // no ambiguity
  },
  vous: {
    pronoun: "vous",
    conjugation: "êtes",
    combined: "vous êtes",
    english: "you are (formal/plural)",
    englishFull: "you are (formal or plural)",
  },
  ils: {
    pronoun: "ils",
    conjugation: "sont",
    combined: "ils sont",
    english: "they are (masculine)",
    englishFull: "they are (masculine or mixed)",
  },
  elles: {
    pronoun: "elles",
    conjugation: "sont",
    combined: "elles sont",
    english: "they are (feminine)",
    englishFull: "they are (all feminine)",
  },
};

// Verb avoir (to have) conjugations
export const avoirConjugations = {
  je: {
    pronoun: "je",
    conjugation: "ai",
    combined: "j'ai",
    english: "I have",
    englishFull: "I have", // no ambiguity
    note: "j' before vowel",
  },
  tu: {
    pronoun: "tu",
    conjugation: "as",
    combined: "tu as",
    english: "you have (informal)",
    englishFull: "you have (informal)",
  },
  il: {
    pronoun: "il",
    conjugation: "a",
    combined: "il a",
    english: "he has",
    englishFull: "he has", // no ambiguity
  },
  elle: {
    pronoun: "elle",
    conjugation: "a",
    combined: "elle a",
    english: "she has",
    englishFull: "she has", // no ambiguity
  },
  nous: {
    pronoun: "nous",
    conjugation: "avons",
    combined: "nous avons",
    english: "we have",
    englishFull: "we have", // no ambiguity
  },
  vous: {
    pronoun: "vous",
    conjugation: "avez",
    combined: "vous avez",
    english: "you have (formal/plural)",
    englishFull: "you have (formal or plural)",
  },
  ils: {
    pronoun: "ils",
    conjugation: "ont",
    combined: "ils ont",
    english: "they have (masculine)",
    englishFull: "they have (masculine or mixed)",
  },
  elles: {
    pronoun: "elles",
    conjugation: "ont",
    combined: "elles ont",
    english: "they have (feminine)",
    englishFull: "they have (all feminine)",
  },
};

// Verb faire (to do/make) conjugations
export const faireConjugations = {
  je: {
    pronoun: "je",
    conjugation: "fais",
    combined: "je fais",
    english: "I do/make",
    englishFull: "I do / I make / I am doing",
  },
  tu: {
    pronoun: "tu",
    conjugation: "fais",
    combined: "tu fais",
    english: "you do/make (informal)",
    englishFull: "you do / you make (informal)",
  },
  il: {
    pronoun: "il",
    conjugation: "fait",
    combined: "il fait",
    english: "he does/makes",
    englishFull: "he does / he makes",
  },
  elle: {
    pronoun: "elle",
    conjugation: "fait",
    combined: "elle fait",
    english: "she does/makes",
    englishFull: "she does / she makes",
  },
  nous: {
    pronoun: "nous",
    conjugation: "faisons",
    combined: "nous faisons",
    english: "we do/make",
    englishFull: "we do / we make",
  },
  vous: {
    pronoun: "vous",
    conjugation: "faites",
    combined: "vous faites",
    english: "you do/make (formal/plural)",
    englishFull: "you do / you make (formal or plural)",
  },
  ils: {
    pronoun: "ils",
    conjugation: "font",
    combined: "ils font",
    english: "they do/make (masculine)",
    englishFull: "they do / they make (masculine or mixed)",
  },
  elles: {
    pronoun: "elles",
    conjugation: "font",
    combined: "elles font",
    english: "they do/make (feminine)",
    englishFull: "they do / they make (all feminine)",
  },
};

// Verb vouloir (to want) conjugations
export const vouloirConjugations = {
  je: {
    pronoun: "je",
    conjugation: "veux",
    combined: "je veux",
    english: "I want",
    englishFull: "I want",
  },
  tu: {
    pronoun: "tu",
    conjugation: "veux",
    combined: "tu veux",
    english: "you want (informal)",
    englishFull: "you want (informal)",
  },
  il: {
    pronoun: "il",
    conjugation: "veut",
    combined: "il veut",
    english: "he wants",
    englishFull: "he wants",
  },
  elle: {
    pronoun: "elle",
    conjugation: "veut",
    combined: "elle veut",
    english: "she wants",
    englishFull: "she wants",
  },
  nous: {
    pronoun: "nous",
    conjugation: "voulons",
    combined: "nous voulons",
    english: "we want",
    englishFull: "we want",
  },
  vous: {
    pronoun: "vous",
    conjugation: "voulez",
    combined: "vous voulez",
    english: "you want (formal/plural)",
    englishFull: "you want (formal or plural)",
  },
  ils: {
    pronoun: "ils",
    conjugation: "veulent",
    combined: "ils veulent",
    english: "they want (masculine)",
    englishFull: "they want (masculine or mixed)",
  },
  elles: {
    pronoun: "elles",
    conjugation: "veulent",
    combined: "elles veulent",
    english: "they want (feminine)",
    englishFull: "they want (all feminine)",
  },
};

// Verb pouvoir (can) conjugations
export const pouvoirConjugations = {
  je: {
    pronoun: "je",
    conjugation: "peux",
    combined: "je peux",
    english: "I can",
    englishFull: "I can",
  },
  tu: {
    pronoun: "tu",
    conjugation: "peux",
    combined: "tu peux",
    english: "you can (informal)",
    englishFull: "you can (informal)",
  },
  il: {
    pronoun: "il",
    conjugation: "peut",
    combined: "il peut",
    english: "he can",
    englishFull: "he can",
  },
  elle: {
    pronoun: "elle",
    conjugation: "peut",
    combined: "elle peut",
    english: "she can",
    englishFull: "she can",
  },
  nous: {
    pronoun: "nous",
    conjugation: "pouvons",
    combined: "nous pouvons",
    english: "we can",
    englishFull: "we can",
  },
  vous: {
    pronoun: "vous",
    conjugation: "pouvez",
    combined: "vous pouvez",
    english: "you can (formal/plural)",
    englishFull: "you can (formal or plural)",
  },
  ils: {
    pronoun: "ils",
    conjugation: "peuvent",
    combined: "ils peuvent",
    english: "they can (masculine)",
    englishFull: "they can (masculine or mixed)",
  },
  elles: {
    pronoun: "elles",
    conjugation: "peuvent",
    combined: "elles peuvent",
    english: "they can (feminine)",
    englishFull: "they can (all feminine)",
  },
};

// Verb devoir (must/to have to) conjugations
export const devoirConjugations = {
  je: {
    pronoun: "je",
    conjugation: "dois",
    combined: "je dois",
    english: "I must",
    englishFull: "I must / I have to",
  },
  tu: {
    pronoun: "tu",
    conjugation: "dois",
    combined: "tu dois",
    english: "you must (informal)",
    englishFull: "you must / you have to (informal)",
  },
  il: {
    pronoun: "il",
    conjugation: "doit",
    combined: "il doit",
    english: "he must",
    englishFull: "he must / he has to",
  },
  elle: {
    pronoun: "elle",
    conjugation: "doit",
    combined: "elle doit",
    english: "she must",
    englishFull: "she must / she has to",
  },
  nous: {
    pronoun: "nous",
    conjugation: "devons",
    combined: "nous devons",
    english: "we must",
    englishFull: "we must / we have to",
  },
  vous: {
    pronoun: "vous",
    conjugation: "devez",
    combined: "vous devez",
    english: "you must (formal/plural)",
    englishFull: "you must / you have to (formal or plural)",
  },
  ils: {
    pronoun: "ils",
    conjugation: "doivent",
    combined: "ils doivent",
    english: "they must (masculine)",
    englishFull: "they must / they have to (masculine or mixed)",
  },
  elles: {
    pronoun: "elles",
    conjugation: "doivent",
    combined: "elles doivent",
    english: "they must (feminine)",
    englishFull: "they must / they have to (all feminine)",
  },
};

// Verb parler (to speak) conjugations
export const parlerConjugations = {
  je: {
    pronoun: "je",
    conjugation: "parle",
    combined: "je parle",
    english: "I speak",
    englishFull: "I speak / I talk",
  },
  tu: {
    pronoun: "tu",
    conjugation: "parles",
    combined: "tu parles",
    english: "you speak (informal)",
    englishFull: "you speak / you talk (informal)",
  },
  il: {
    pronoun: "il",
    conjugation: "parle",
    combined: "il parle",
    english: "he speaks",
    englishFull: "he speaks / he talks",
  },
  elle: {
    pronoun: "elle",
    conjugation: "parle",
    combined: "elle parle",
    english: "she speaks",
    englishFull: "she speaks / she talks",
  },
  nous: {
    pronoun: "nous",
    conjugation: "parlons",
    combined: "nous parlons",
    english: "we speak",
    englishFull: "we speak / we talk",
  },
  vous: {
    pronoun: "vous",
    conjugation: "parlez",
    combined: "vous parlez",
    english: "you speak (formal/plural)",
    englishFull: "you speak / you talk (formal or plural)",
  },
  ils: {
    pronoun: "ils",
    conjugation: "parlent",
    combined: "ils parlent",
    english: "they speak (masculine)",
    englishFull: "they speak / they talk (masculine or mixed)",
  },
  elles: {
    pronoun: "elles",
    conjugation: "parlent",
    combined: "elles parlent",
    english: "they speak (feminine)",
    englishFull: "they speak / they talk (all feminine)",
  },
};

// Verb aller (to go) conjugations
export const allerConjugations = {
  je: {
    pronoun: "je",
    conjugation: "vais",
    combined: "je vais",
    english: "I go",
    englishFull: "I go / I am going",
  },
  tu: {
    pronoun: "tu",
    conjugation: "vas",
    combined: "tu vas",
    english: "you go (informal)",
    englishFull: "you go / you are going (informal)",
  },
  il: {
    pronoun: "il",
    conjugation: "va",
    combined: "il va",
    english: "he goes",
    englishFull: "he goes / he is going",
  },
  elle: {
    pronoun: "elle",
    conjugation: "va",
    combined: "elle va",
    english: "she goes",
    englishFull: "she goes / she is going",
  },
  nous: {
    pronoun: "nous",
    conjugation: "allons",
    combined: "nous allons",
    english: "we go",
    englishFull: "we go / we are going",
  },
  vous: {
    pronoun: "vous",
    conjugation: "allez",
    combined: "vous allez",
    english: "you go (formal/plural)",
    englishFull: "you go / you are going (formal or plural)",
  },
  ils: {
    pronoun: "ils",
    conjugation: "vont",
    combined: "ils vont",
    english: "they go (masculine)",
    englishFull: "they go / they are going (masculine or mixed)",
  },
  elles: {
    pronoun: "elles",
    conjugation: "vont",
    combined: "elles vont",
    english: "they go (feminine)",
    englishFull: "they go / they are going (all feminine)",
  },
};

// Verb venir (to come) conjugations
export const venirConjugations = {
  je: {
    pronoun: "je",
    conjugation: "viens",
    combined: "je viens",
    english: "I come",
    englishFull: "I come / I am coming",
  },
  tu: {
    pronoun: "tu",
    conjugation: "viens",
    combined: "tu viens",
    english: "you come (informal)",
    englishFull: "you come / you are coming (informal)",
  },
  il: {
    pronoun: "il",
    conjugation: "vient",
    combined: "il vient",
    english: "he comes",
    englishFull: "he comes / he is coming",
  },
  elle: {
    pronoun: "elle",
    conjugation: "vient",
    combined: "elle vient",
    english: "she comes",
    englishFull: "she comes / she is coming",
  },
  nous: {
    pronoun: "nous",
    conjugation: "venons",
    combined: "nous venons",
    english: "we come",
    englishFull: "we come / we are coming",
  },
  vous: {
    pronoun: "vous",
    conjugation: "venez",
    combined: "vous venez",
    english: "you come (formal/plural)",
    englishFull: "you come / you are coming (formal or plural)",
  },
  ils: {
    pronoun: "ils",
    conjugation: "viennent",
    combined: "ils viennent",
    english: "they come (masculine)",
    englishFull: "they come / they are coming (masculine or mixed)",
  },
  elles: {
    pronoun: "elles",
    conjugation: "viennent",
    combined: "elles viennent",
    english: "they come (feminine)",
    englishFull: "they come / they are coming (all feminine)",
  },
};

// Verb partir (to leave) conjugations
export const partirConjugations = {
  je: {
    pronoun: "je",
    conjugation: "pars",
    combined: "je pars",
    english: "I leave",
    englishFull: "I leave / I am leaving",
  },
  tu: {
    pronoun: "tu",
    conjugation: "pars",
    combined: "tu pars",
    english: "you leave (informal)",
    englishFull: "you leave / you are leaving (informal)",
  },
  il: {
    pronoun: "il",
    conjugation: "part",
    combined: "il part",
    english: "he leaves",
    englishFull: "he leaves / he is leaving",
  },
  elle: {
    pronoun: "elle",
    conjugation: "part",
    combined: "elle part",
    english: "she leaves",
    englishFull: "she leaves / she is leaving",
  },
  nous: {
    pronoun: "nous",
    conjugation: "partons",
    combined: "nous partons",
    english: "we leave",
    englishFull: "we leave / we are leaving",
  },
  vous: {
    pronoun: "vous",
    conjugation: "partez",
    combined: "vous partez",
    english: "you leave (formal/plural)",
    englishFull: "you leave / you are leaving (formal or plural)",
  },
  ils: {
    pronoun: "ils",
    conjugation: "partent",
    combined: "ils partent",
    english: "they leave (masculine)",
    englishFull: "they leave / they are leaving (masculine or mixed)",
  },
  elles: {
    pronoun: "elles",
    conjugation: "partent",
    combined: "elles partent",
    english: "they leave (feminine)",
    englishFull: "they leave / they are leaving (all feminine)",
  },
};

// Verb arriver (to arrive) conjugations
export const arriverConjugations = {
  je: {
    pronoun: "je",
    conjugation: "arrive",
    combined: "j'arrive",
    english: "I arrive",
    englishFull: "I arrive / I am arriving",
    note: "j' before vowel",
  },
  tu: {
    pronoun: "tu",
    conjugation: "arrives",
    combined: "tu arrives",
    english: "you arrive (informal)",
    englishFull: "you arrive / you are arriving (informal)",
  },
  il: {
    pronoun: "il",
    conjugation: "arrive",
    combined: "il arrive",
    english: "he arrives",
    englishFull: "he arrives / he is arriving",
  },
  elle: {
    pronoun: "elle",
    conjugation: "arrive",
    combined: "elle arrive",
    english: "she arrives",
    englishFull: "she arrives / she is arriving",
  },
  nous: {
    pronoun: "nous",
    conjugation: "arrivons",
    combined: "nous arrivons",
    english: "we arrive",
    englishFull: "we arrive / we are arriving",
  },
  vous: {
    pronoun: "vous",
    conjugation: "arrivez",
    combined: "vous arrivez",
    english: "you arrive (formal/plural)",
    englishFull: "you arrive / you are arriving (formal or plural)",
  },
  ils: {
    pronoun: "ils",
    conjugation: "arrivent",
    combined: "ils arrivent",
    english: "they arrive (masculine)",
    englishFull: "they arrive / they are arriving (masculine or mixed)",
  },
  elles: {
    pronoun: "elles",
    conjugation: "arrivent",
    combined: "elles arrivent",
    english: "they arrive (feminine)",
    englishFull: "they arrive / they are arriving (all feminine)",
  },
};

// Verb rester (to stay) conjugations
export const resterConjugations = {
  je: {
    pronoun: "je",
    conjugation: "reste",
    combined: "je reste",
    english: "I stay",
    englishFull: "I stay / I am staying",
  },
  tu: {
    pronoun: "tu",
    conjugation: "restes",
    combined: "tu restes",
    english: "you stay (informal)",
    englishFull: "you stay / you are staying (informal)",
  },
  il: {
    pronoun: "il",
    conjugation: "reste",
    combined: "il reste",
    english: "he stays",
    englishFull: "he stays / he is staying",
  },
  elle: {
    pronoun: "elle",
    conjugation: "reste",
    combined: "elle reste",
    english: "she stays",
    englishFull: "she stays / she is staying",
  },
  nous: {
    pronoun: "nous",
    conjugation: "restons",
    combined: "nous restons",
    english: "we stay",
    englishFull: "we stay / we are staying",
  },
  vous: {
    pronoun: "vous",
    conjugation: "restez",
    combined: "vous restez",
    english: "you stay (formal/plural)",
    englishFull: "you stay / you are staying (formal or plural)",
  },
  ils: {
    pronoun: "ils",
    conjugation: "restent",
    combined: "ils restent",
    english: "they stay (masculine)",
    englishFull: "they stay / they are staying (masculine or mixed)",
  },
  elles: {
    pronoun: "elles",
    conjugation: "restent",
    combined: "elles restent",
    english: "they stay (feminine)",
    englishFull: "they stay / they are staying (all feminine)",
  },
};

// Verb voir (to see) conjugations
export const voirConjugations = {
  je: {
    pronoun: "je",
    conjugation: "vois",
    combined: "je vois",
    english: "I see",
    englishFull: "I see / I am seeing",
  },
  tu: {
    pronoun: "tu",
    conjugation: "vois",
    combined: "tu vois",
    english: "you see (informal)",
    englishFull: "you see / you are seeing (informal)",
  },
  il: {
    pronoun: "il",
    conjugation: "voit",
    combined: "il voit",
    english: "he sees",
    englishFull: "he sees / he is seeing",
  },
  elle: {
    pronoun: "elle",
    conjugation: "voit",
    combined: "elle voit",
    english: "she sees",
    englishFull: "she sees / she is seeing",
  },
  nous: {
    pronoun: "nous",
    conjugation: "voyons",
    combined: "nous voyons",
    english: "we see",
    englishFull: "we see / we are seeing",
  },
  vous: {
    pronoun: "vous",
    conjugation: "voyez",
    combined: "vous voyez",
    english: "you see (formal/plural)",
    englishFull: "you see / you are seeing (formal or plural)",
  },
  ils: {
    pronoun: "ils",
    conjugation: "voient",
    combined: "ils voient",
    english: "they see (masculine)",
    englishFull: "they see / they are seeing (masculine or mixed)",
  },
  elles: {
    pronoun: "elles",
    conjugation: "voient",
    combined: "elles voient",
    english: "they see (feminine)",
    englishFull: "they see / they are seeing (all feminine)",
  },
};

// Question words and common phrases
export const questionWords = {
  que: { french: "que", english: "what", variant: "quoi" },
  qui: { french: "qui", english: "who" },
  ou: { french: "où", english: "where", note: "with accent" },
  quand: { french: "quand", english: "when" },
  comment: { french: "comment", english: "how" },
  pourquoi: { french: "pourquoi", english: "why" },
  combien: {
    french: "combien",
    english: "how much/how many",
    note: "quantity and price",
  },
};

export const commonPhrases = {
  questCeQueCest: {
    french: "qu'est-ce que c'est",
    english: "what is it",
    simplified: "quest-ce que cest",
  },
  commentCaVa: {
    french: "comment ça va",
    english: "how are you / how's it going",
    simplified: "comment ca va",
  },
  ouEstCe: {
    french: "où est-ce",
    english: "where is it",
    simplified: "ou est-ce",
  },
  combienEstCe: {
    french: "combien est-ce",
    english: "how much is it",
    simplified: "combien est-ce",
    note: "useful for shopping",
  },
  cestCombien: {
    french: "c'est combien",
    english: "how much is it",
    simplified: "cest combien",
    note: "informal alternative",
  },
};

/**
 * Helper to generate wrong answer feedback
 */
// Demonstratives - "it, that, this, these, those"
export const demonstratives = {
  ce: {
    french: "ce",
    english: "this/that (masc + consonant)",
    englishFull: "this/that (masculine, before consonant sound)",
    type: "demonstrative",
    gender: "masculine",
    note: "before consonant sounds: b, c, d, f, g, k, etc.",
  },
  cet: {
    french: "cet",
    english: "this/that (masc + vowel)",
    englishFull: "this/that (masculine, before vowel sound)",
    type: "demonstrative",
    gender: "masculine",
    note: "before vowel sounds: a, e, i, o, u, silent h",
  },
  cette: {
    french: "cette",
    english: "this/that (feminine)",
    englishFull: "this/that (feminine)",
    type: "demonstrative",
    gender: "feminine",
    note: "feminine nouns",
  },
  ces: {
    french: "ces",
    english: "these/those",
    englishFull: "these/those (plural)",
    type: "demonstrative",
    gender: "plural",
    note: "plural",
  },
  ca: {
    french: "ça",
    english: "that/it (informal)",
    englishFull: "that/it (informal - most common!)",
    type: "demonstrative",
    note: "informal, very common",
  },
  ceci: {
    french: "ceci",
    english: "this (formal)",
    englishFull: "this (formal)",
    type: "demonstrative",
    note: "formal",
  },
  cela: {
    french: "cela",
    english: "that (formal)",
    englishFull: "that (formal)",
    type: "demonstrative",
    note: "formal",
  },
};

// Object pronouns - "me, you, him, her, it, us, them"
export const objectPronouns = {
  me: {
    french: "me",
    english: "me",
    englishFull: "me", // no ambiguity
    type: "object",
    person: "first",
    number: "singular",
  },
  te: {
    french: "te",
    english: "you (informal)",
    englishFull: "you (informal)",
    type: "object",
    person: "second",
    number: "singular",
  },
  le: {
    french: "le",
    english: "him/it (masculine)",
    englishFull: "him/it (masculine)",
    type: "object",
    person: "third",
    number: "singular",
    gender: "masculine",
  },
  la: {
    french: "la",
    english: "her/it (feminine)",
    englishFull: "her/it (feminine)",
    type: "object",
    person: "third",
    number: "singular",
    gender: "feminine",
  },
  nous_obj: {
    french: "nous",
    english: "us",
    englishFull: "us", // no ambiguity
    type: "object",
    person: "first",
    number: "plural",
  },
  vous_obj: {
    french: "vous",
    english: "you (formal/plural)",
    englishFull: "you (formal or plural)",
    type: "object",
    person: "second",
    number: "plural",
  },
  les: {
    french: "les",
    english: "them",
    englishFull: "them", // no ambiguity
    type: "object",
    person: "third",
    number: "plural",
  },
};

// Possessive adjectives - "my, your, his, her, our, their"
export const possessiveAdjectives = {
  mon: {
    french: "mon",
    english: "my (masculine)",
    englishFull: "my (masculine, like 'mon livre')",
    type: "possessive",
    owner: "je",
    gender: "masculine",
    number: "singular",
  },
  ma: {
    french: "ma",
    english: "my (feminine)",
    englishFull: "my (feminine, like 'ma maison')",
    type: "possessive",
    owner: "je",
    gender: "feminine",
    number: "singular",
  },
  mes: {
    french: "mes",
    english: "my (plural)",
    englishFull: "my (plural, like 'mes livres')",
    type: "possessive",
    owner: "je",
    number: "plural",
  },
  ton: {
    french: "ton",
    english: "your (masc, informal)",
    englishFull: "your (informal, masculine like 'ton chat')",
    type: "possessive",
    owner: "tu",
    gender: "masculine",
    number: "singular",
  },
  ta: {
    french: "ta",
    english: "your (fem, informal)",
    englishFull: "your (informal, feminine like 'ta voiture')",
    type: "possessive",
    owner: "tu",
    gender: "feminine",
    number: "singular",
  },
  tes: {
    french: "tes",
    english: "your (plural, informal)",
    englishFull: "your (informal, plural like 'tes amis')",
    type: "possessive",
    owner: "tu",
    number: "plural",
  },
  son: {
    french: "son",
    english: "his/her (masculine)",
    englishFull: "his/her (masculine, like 'son livre')",
    type: "possessive",
    owner: "il/elle",
    gender: "masculine",
    number: "singular",
  },
  sa: {
    french: "sa",
    english: "his/her (feminine)",
    englishFull: "his/her (feminine, like 'sa maison')",
    type: "possessive",
    owner: "il/elle",
    gender: "feminine",
    number: "singular",
  },
  ses: {
    french: "ses",
    english: "his/her (plural)",
    englishFull: "his/her (plural, like 'ses chats')",
    type: "possessive",
    owner: "il/elle",
    number: "plural",
  },
  notre: {
    french: "notre",
    english: "our (singular)",
    englishFull: "our (singular, like 'notre maison')",
    type: "possessive",
    owner: "nous",
    number: "singular",
  },
  nos: {
    french: "nos",
    english: "our (plural)",
    englishFull: "our (plural, like 'nos chats')",
    type: "possessive",
    owner: "nous",
    number: "plural",
  },
  votre: {
    french: "votre",
    english: "your (formal, singular)",
    englishFull: "your (formal, singular like 'votre livre')",
    type: "possessive",
    owner: "vous",
    number: "singular",
  },
  vos: {
    french: "vos",
    english: "your (formal, plural)",
    englishFull: "your (formal, plural like 'vos livres')",
    type: "possessive",
    owner: "vous",
    number: "plural",
  },
  leur: {
    french: "leur",
    english: "their (singular)",
    englishFull: "their (singular, like 'leur chat')",
    type: "possessive",
    owner: "ils/elles",
    number: "singular",
  },
  leurs: {
    french: "leurs",
    english: "their (plural)",
    englishFull: "their (plural, like 'leurs chats')",
    type: "possessive",
    owner: "ils/elles",
    number: "plural",
  },
};

// Possessive pronouns - "mine, yours, his, hers, ours, theirs"
export const possessivePronouns = {
  le_mien: {
    french: "le mien",
    english: "mine (masculine)",
    englishFull: "mine (masculine thing)",
    type: "possessive_pronoun",
    owner: "je",
    gender: "masculine",
  },
  la_mienne: {
    french: "la mienne",
    english: "mine (feminine)",
    englishFull: "mine (feminine thing)",
    type: "possessive_pronoun",
    owner: "je",
    gender: "feminine",
  },
  le_tien: {
    french: "le tien",
    english: "yours (masc, informal)",
    englishFull: "yours (informal, masculine thing)",
    type: "possessive_pronoun",
    owner: "tu",
    gender: "masculine",
  },
  la_tienne: {
    french: "la tienne",
    english: "yours (fem, informal)",
    englishFull: "yours (informal, feminine thing)",
    type: "possessive_pronoun",
    owner: "tu",
    gender: "feminine",
  },
  le_sien: {
    french: "le sien",
    english: "his/hers (masculine)",
    englishFull: "his/hers (masculine thing)",
    type: "possessive_pronoun",
    owner: "il/elle",
    gender: "masculine",
  },
  la_sienne: {
    french: "la sienne",
    english: "his/hers (feminine)",
    englishFull: "his/hers (feminine thing)",
    type: "possessive_pronoun",
    owner: "il/elle",
    gender: "feminine",
  },
  le_notre: {
    french: "le nôtre",
    english: "ours (masculine)",
    englishFull: "ours (masculine thing)",
    type: "possessive_pronoun",
    owner: "nous",
    gender: "masculine",
  },
  la_notre: {
    french: "la nôtre",
    english: "ours (feminine)",
    englishFull: "ours (feminine thing)",
    type: "possessive_pronoun",
    owner: "nous",
    gender: "feminine",
  },
  le_votre: {
    french: "le vôtre",
    english: "yours (formal, masculine)",
    englishFull: "yours (formal, masculine thing)",
    type: "possessive_pronoun",
    owner: "vous",
    gender: "masculine",
  },
  la_votre: {
    french: "la vôtre",
    english: "yours (formal, feminine)",
    englishFull: "yours (formal, feminine thing)",
    type: "possessive_pronoun",
    owner: "vous",
    gender: "feminine",
  },
  le_leur: {
    french: "le leur",
    english: "theirs (masculine)",
    englishFull: "theirs (masculine thing)",
    type: "possessive_pronoun",
    owner: "ils/elles",
    gender: "masculine",
  },
  la_leur: {
    french: "la leur",
    english: "theirs (feminine)",
    englishFull: "theirs (feminine thing)",
    type: "possessive_pronoun",
    owner: "ils/elles",
    gender: "feminine",
  },
};

// Common Nouns - Essential vocabulary from top 100 words
export const commonNouns = {
  livre: {
    french: "livre",
    english: "book",
    englishFull: "book",
    gender: "masculine",
    article: "un livre / le livre",
  },
  chat: {
    french: "chat",
    english: "cat (masculine)",
    englishFull: "cat (male)",
    gender: "masculine",
    article: "un chat / le chat",
  },
  chatte: {
    french: "chatte",
    english: "cat (feminine)",
    englishFull: "cat (female)",
    gender: "feminine",
    article: "une chatte / la chatte",
  },
  chien: {
    french: "chien",
    english: "dog (masculine)",
    englishFull: "dog (male)",
    gender: "masculine",
    article: "un chien / le chien",
  },
  chienne: {
    french: "chienne",
    english: "dog (feminine)",
    englishFull: "dog (female)",
    gender: "feminine",
    article: "une chienne / la chienne",
  },
  maison: {
    french: "maison",
    english: "house",
    englishFull: "house",
    gender: "feminine",
    article: "une maison / la maison",
  },
  voiture: {
    french: "voiture",
    english: "car",
    englishFull: "car",
    gender: "feminine",
    article: "une voiture / la voiture",
  },
  ami: {
    french: "ami",
    english: "friend (masculine)",
    englishFull: "friend (masculine)",
    gender: "masculine",
    article: "un ami / l'ami",
  },
  amie: {
    french: "amie",
    english: "friend (feminine)",
    englishFull: "friend (feminine)",
    gender: "feminine",
    article: "une amie / l'amie",
  },
  homme: {
    french: "homme",
    english: "man",
    englishFull: "man",
    gender: "masculine",
    article: "un homme / l'homme",
    note: "silent h",
  },
  femme: {
    french: "femme",
    english: "woman",
    englishFull: "woman",
    gender: "feminine",
    article: "une femme / la femme",
  },
  enfant: {
    french: "enfant",
    english: "child",
    englishFull: "child",
    gender: "masculine/feminine",
    article: "un enfant / une enfant",
    note: "same word both genders",
  },
  chose: {
    french: "chose",
    english: "thing",
    englishFull: "thing",
    gender: "feminine",
    article: "une chose / la chose",
  },
  jour: {
    french: "jour",
    english: "day",
    englishFull: "day",
    gender: "masculine",
    article: "un jour / le jour",
  },
  temps: {
    french: "temps",
    english: "time/weather",
    englishFull: "time/weather",
    gender: "masculine",
    article: "le temps",
    note: "can mean time OR weather",
  },
  vie: {
    french: "vie",
    english: "life",
    englishFull: "life",
    gender: "feminine",
    article: "la vie",
  },
  monde: {
    french: "monde",
    english: "world",
    englishFull: "world",
    gender: "masculine",
    article: "le monde",
    note: "tout le monde = everyone",
  },
  eau: {
    french: "eau",
    english: "water",
    englishFull: "water",
    gender: "feminine",
    article: "l'eau",
  },
  pain: {
    french: "pain",
    english: "bread",
    englishFull: "bread",
    gender: "masculine",
    article: "le pain",
  },
  argent: {
    french: "argent",
    english: "money",
    englishFull: "money",
    gender: "masculine",
    article: "l'argent",
    note: "also means silver",
  },
  travail: {
    french: "travail",
    english: "work",
    englishFull: "work",
    gender: "masculine",
    article: "le travail",
  },
  ville: {
    french: "ville",
    english: "city",
    englishFull: "city",
    gender: "feminine",
    article: "la ville",
  },
  place: {
    french: "place",
    english: "square/place",
    englishFull: "square/place",
    gender: "feminine",
    article: "la place",
  },
  rue: {
    french: "rue",
    english: "street",
    englishFull: "street",
    gender: "feminine",
    article: "la rue",
  },
  table: {
    french: "table",
    english: "table",
    englishFull: "table",
    gender: "feminine",
    article: "la table",
  },
  main: {
    french: "main",
    english: "hand",
    englishFull: "hand",
    gender: "feminine",
    article: "la main",
  },
  tete: {
    french: "tête",
    english: "head",
    englishFull: "head",
    gender: "feminine",
    article: "la tête",
  },
  nom: {
    french: "nom",
    english: "name",
    englishFull: "name",
    gender: "masculine",
    article: "le nom",
  },
  porte: {
    french: "porte",
    english: "door",
    englishFull: "door",
    gender: "feminine",
    article: "la porte",
  },
  personne: {
    french: "personne",
    english: "nobody/no one",
    englishFull: "nobody/no one",
    gender: "feminine",
    article: "personne",
    note: "often used with ne: je ne vois personne",
  },
  carteDeCredit: {
    french: "carte de crédit",
    english: "credit card",
    englishFull: "credit card",
    gender: "feminine",
    article: "la carte de crédit / une carte de crédit",
  },
  especes: {
    french: "espèces",
    english: "cash",
    englishFull: "cash",
    gender: "feminine",
    article: "les espèces / des espèces",
    note: "plural - payer en espèces",
  },
  carafeDeau: {
    french: "carafe d'eau",
    english: "carafe of water",
    englishFull: "carafe of water",
    gender: "feminine",
    article: "une carafe d'eau / la carafe d'eau",
  },
  addition: {
    french: "addition",
    english: "bill/check",
    englishFull: "the bill/check (at restaurant)",
    gender: "feminine",
    article: "l'addition",
    note: "used in restaurants",
  },
};

// Common Adjectives - Essential descriptive words from top 100
export const commonAdjectives = {
  bon: {
    french: "bon",
    englishMasc: "good (masculine)",
    englishFem: "good (feminine)",
    femForm: "bonne",
    example: "un bon livre / une bonne maison",
    note: "very common, doubles n in feminine",
  },
  grand: {
    french: "grand",
    englishMasc: "big/tall (masculine)",
    englishFem: "big/tall (feminine)",
    femForm: "grande",
    example: "un grand homme / une grande femme",
    note: "can mean big or tall",
  },
  petit: {
    french: "petit",
    englishMasc: "small (masculine)",
    englishFem: "small (feminine)",
    femForm: "petite",
    example: "un petit chat / une petite maison",
    note: "very common",
  },
  nouveau: {
    french: "nouveau",
    englishMasc: "new (masculine)",
    englishFem: "new (feminine)",
    femForm: "nouvelle",
    example: "un nouveau livre / une nouvelle voiture",
    note: "irregular feminine form",
  },
  vieux: {
    french: "vieux",
    englishMasc: "old (masculine)",
    englishFem: "old (feminine)",
    femForm: "vieille",
    example: "un vieux chat / une vieille maison",
    note: "irregular feminine form",
  },
  jeune: {
    french: "jeune",
    englishMasc: "young",
    englishFem: "young",
    femForm: "jeune",
    example: "un jeune homme / une jeune femme",
    note: "same form both genders",
  },
  beau: {
    french: "beau",
    englishMasc: "beautiful (masculine)",
    englishFem: "beautiful (feminine)",
    femForm: "belle",
    example: "un beau livre / une belle maison",
    note: "irregular feminine form",
  },
  autre: {
    french: "autre",
    englishMasc: "other",
    englishFem: "other",
    femForm: "autre",
    example: "un autre livre / une autre maison",
    note: "same form both genders",
  },
};

// Connectors and Simple Modifiers - "and, but, or, also, very"
export const connectors = {
  et: {
    french: "et",
    english: "and",
    englishFull: "and",
    type: "connector",
    category: "conjunction",
    example: "un chat et un chien",
    note: "most common connector",
  },
  mais: {
    french: "mais",
    english: "but",
    englishFull: "but",
    type: "connector",
    category: "conjunction",
    example: "je veux un chat, mais j'ai un chien",
    note: "shows contrast",
  },
  ou: {
    french: "ou",
    english: "or",
    englishFull: "or",
    type: "connector",
    category: "conjunction",
    example: "un chat ou un chien?",
    note: "presents a choice",
  },
  aussi: {
    french: "aussi",
    english: "also/too",
    englishFull: "also / too",
    type: "adverb",
    category: "addition",
    example: "j'ai un chat aussi",
    note: "very common!",
  },
  très: {
    french: "très",
    english: "very",
    englishFull: "very",
    type: "adverb",
    category: "intensity",
    example: "très bon",
    note: "super simple modifier",
  },
};

// Prepositions - Essential for building complex sentences
export const prepositions = {
  avec: {
    french: "avec",
    english: "with",
    englishFull: "with",
    type: "preposition",
    example: "avec moi, avec le chat",
    note: "use with stressed pronouns",
  },
  dans: {
    french: "dans",
    english: "in",
    englishFull: "in",
    type: "preposition",
    example: "dans la maison, dans la rue",
    note: "physical location inside",
  },
  sur: {
    french: "sur",
    english: "on",
    englishFull: "on",
    type: "preposition",
    example: "sur la table, sur la voiture",
    note: "physical location on top",
  },
  à: {
    french: "à",
    english: "to/at",
    englishFull: "to/at",
    type: "preposition",
    example: "à Paris, à la maison",
    note: "location or direction",
  },
  de: {
    french: "de",
    english: "of/from",
    englishFull: "of/from",
    type: "preposition",
    example: "de Paris, le livre de Marie",
    note: "origin or possession",
  },
  pour: {
    french: "pour",
    english: "for",
    englishFull: "for",
    type: "preposition",
    example: "pour toi, pour le pain",
    note: "purpose or recipient",
  },
  en: {
    french: "en",
    english: "in/by",
    englishFull: "in/by",
    type: "preposition",
    example: "en France, en espèces",
    note: "used with countries, manner",
  },
  sans: {
    french: "sans",
    english: "without",
    englishFull: "without",
    type: "preposition",
    example: "sans toi, sans argent",
    note: "absence or lack",
  },
};

// Stressed Pronouns - Used after prepositions
export const stressedPronouns = {
  moi: {
    french: "moi",
    english: "me",
    englishFull: "me (stressed)",
    type: "stressed pronoun",
    person: "first singular",
    example: "avec moi, pour moi",
    note: "use after prepositions",
  },
  toi: {
    french: "toi",
    english: "you",
    englishFull: "you (stressed)",
    type: "stressed pronoun",
    person: "second singular",
    example: "avec toi, pour toi",
    note: "informal",
  },
  lui: {
    french: "lui",
    english: "him",
    englishFull: "him (stressed)",
    type: "stressed pronoun",
    person: "third singular",
    gender: "masculine",
    example: "avec lui, pour lui",
    note: "masculine",
  },
  elle: {
    french: "elle",
    english: "her",
    englishFull: "her (stressed)",
    type: "stressed pronoun",
    person: "third singular",
    gender: "feminine",
    example: "avec elle, pour elle",
    note: "feminine",
  },
  nous: {
    french: "nous",
    english: "us",
    englishFull: "us (stressed)",
    type: "stressed pronoun",
    person: "first plural",
    example: "avec nous, pour nous",
    note: "same as subject pronoun",
  },
  vous: {
    french: "vous",
    english: "you",
    englishFull: "you (stressed)",
    type: "stressed pronoun",
    person: "second plural",
    example: "avec vous, pour vous",
    note: "formal/plural",
  },
  eux: {
    french: "eux",
    english: "them",
    englishFull: "them (stressed masculine)",
    type: "stressed pronoun",
    person: "third plural",
    gender: "masculine",
    example: "avec eux, pour eux",
    note: "masculine or mixed",
  },
  elles: {
    french: "elles",
    english: "them",
    englishFull: "them (stressed feminine)",
    type: "stressed pronoun",
    person: "third plural",
    gender: "feminine",
    example: "avec elles, pour elles",
    note: "all feminine",
  },
};

// Time Adverbs - Essential for talking about when
export const timeAdverbs = {
  maintenant: {
    french: "maintenant",
    english: "now",
    englishFull: "now",
    type: "adverb",
    category: "time",
    example: "je veux manger maintenant",
    note: "present moment",
  },
  toujours: {
    french: "toujours",
    english: "always",
    englishFull: "always",
    type: "adverb",
    category: "frequency",
    example: "je parle toujours français",
    note: "100% of the time",
  },
  jamais: {
    french: "jamais",
    english: "never",
    englishFull: "never",
    type: "adverb",
    category: "frequency",
    example: "je ne vais jamais là-bas",
    note: "used with 'ne' for negation",
  },
  aujourdhui: {
    french: "aujourd'hui",
    english: "today",
    englishFull: "today",
    type: "adverb",
    category: "time",
    example: "aujourd'hui je suis ici",
    note: "this day",
  },
  demain: {
    french: "demain",
    english: "tomorrow",
    englishFull: "tomorrow",
    type: "adverb",
    category: "time",
    example: "je vais partir demain",
    note: "next day",
  },
  hier: {
    french: "hier",
    english: "yesterday",
    englishFull: "yesterday",
    type: "adverb",
    category: "time",
    example: "hier j'ai vu le film",
    note: "previous day",
  },
  souvent: {
    french: "souvent",
    english: "often",
    englishFull: "often",
    type: "adverb",
    category: "frequency",
    example: "je vais souvent au restaurant",
    note: "frequently",
  },
  parfois: {
    french: "parfois",
    english: "sometimes",
    englishFull: "sometimes",
    type: "adverb",
    category: "frequency",
    example: "parfois je mange du pain",
    note: "occasionally",
  },
};

// Location Adverbs - Essential for talking about where
export const locationAdverbs = {
  ici: {
    french: "ici",
    english: "here",
    englishFull: "here",
    type: "adverb",
    category: "location",
    example: "je suis ici maintenant",
    note: "at this place",
  },
  la: {
    french: "là",
    english: "there",
    englishFull: "there",
    type: "adverb",
    category: "location",
    example: "il est là",
    note: "at that place",
  },
  laBas: {
    french: "là-bas",
    english: "over there",
    englishFull: "over there",
    type: "adverb",
    category: "location",
    example: "le restaurant est là-bas",
    note: "at a distant place",
  },
  partout: {
    french: "partout",
    english: "everywhere",
    englishFull: "everywhere",
    type: "adverb",
    category: "location",
    example: "je vois des gens partout",
    note: "in all places",
  },
  quelquePart: {
    french: "quelque part",
    english: "somewhere",
    englishFull: "somewhere",
    type: "adverb",
    category: "location",
    example: "il est quelque part dans la ville",
    note: "in an unspecified place",
  },
  nullePart: {
    french: "nulle part",
    english: "nowhere",
    englishFull: "nowhere",
    type: "adverb",
    category: "location",
    example: "je ne vais nulle part",
    note: "in no place, used with 'ne'",
  },
};

// Survival Phrases - Essential for real-world communication
export const survivalPhrases = {
  jeVoudrais: {
    french: "je voudrais",
    english: "I would like",
    englishFull: "I would like (polite)",
    type: "phrase",
    example: "je voudrais un café, s'il vous plaît",
    note: "polite form of 'je veux'",
  },
  excusezMoi: {
    french: "excusez-moi",
    english: "excuse me",
    englishFull: "excuse me",
    type: "phrase",
    example: "excusez-moi, où est le restaurant?",
    note: "to get attention politely",
  },
  silVousPlait: {
    french: "s'il vous plaît",
    english: "please",
    englishFull: "please (formal)",
    type: "phrase",
    example: "un café, s'il vous plaît",
    note: "formal/polite please",
  },
  silTePlait: {
    french: "s'il te plaît",
    english: "please",
    englishFull: "please (informal)",
    type: "phrase",
    example: "un café, s'il te plaît",
    note: "informal please",
  },
  cestCombien: {
    french: "c'est combien",
    english: "how much is it",
    englishFull: "how much is it?",
    type: "phrase",
    example: "c'est combien pour le pain?",
    note: "asking for price",
  },
  merciBeaucoup: {
    french: "merci beaucoup",
    english: "thank you very much",
    englishFull: "thank you very much",
    type: "phrase",
    example: "merci beaucoup pour aujourd'hui",
    note: "emphatic thanks",
  },
  deRien: {
    french: "de rien",
    english: "you're welcome",
    englishFull: "you're welcome",
    type: "phrase",
    example: "merci! - de rien!",
    note: "response to thanks",
  },
  laddition: {
    french: "l'addition",
    english: "the bill/check",
    englishFull: "the bill/check",
    type: "phrase",
    example: "l'addition, s'il vous plaît",
    note: "at restaurants",
  },
};

// Negation Patterns
export const negationPatterns = {
  nePas: {
    french: "ne...pas",
    english: "not",
    englishFull: "not (negation)",
    type: "negation",
    example: "je ne veux pas",
    note: "basic negation, surrounds verb",
  },
  neJamais: {
    french: "ne...jamais",
    english: "never",
    englishFull: "never (negation)",
    type: "negation",
    example: "je ne vais jamais là-bas",
    note: "replaces 'pas' with 'jamais'",
  },
  nePlus: {
    french: "ne...plus",
    english: "no more/no longer",
    englishFull: "no more / no longer",
    type: "negation",
    example: "je ne veux plus",
    note: "cessation of action",
  },
};

// Comparison Words & Intensity
export const comparisonWords = {
  plus: {
    french: "plus",
    english: "more",
    type: "comparison",
    example: "plus grand (bigger)",
    note: "used with adjectives for comparisons",
  },
  moins: {
    french: "moins",
    english: "less",
    type: "comparison",
    example: "moins cher (less expensive)",
    note: "opposite of 'plus'",
  },
  meilleur: {
    french: "meilleur",
    english: "better (masculine)",
    femForm: "meilleure",
    type: "comparison",
    example: "un meilleur livre / une meilleure maison",
    note: "adjective - agrees with gender",
  },
  leMeilleur: {
    french: "le meilleur",
    english: "the best (masculine)",
    femForm: "la meilleure",
    type: "superlative",
    example: "le meilleur livre / la meilleure maison",
    note: "superlative with article",
  },
  pire: {
    french: "pire",
    english: "worse",
    type: "comparison",
    example: "c'est pire (it's worse)",
    note: "same form both genders",
  },
  laPire: {
    french: "le/la pire",
    english: "the worst",
    type: "superlative",
    example: "la pire chose (the worst thing)",
    note: "superlative with article",
  },
  trop: {
    french: "trop",
    english: "too much / too",
    type: "intensity",
    example: "c'est trop cher (it's too expensive)",
    note: "intensity modifier",
  },
  tout: {
    french: "tout",
    english: "all / everything",
    femForm: "toute",
    pluralMasc: "tous",
    pluralFem: "toutes",
    type: "quantifier",
    example: "tout le monde (everyone), je veux tout (I want everything)",
    note: "agrees with noun",
  },
  meme: {
    french: "même",
    english: "same / even",
    type: "comparison",
    example: "le même livre (the same book), même toi (even you)",
    note: "comparison and emphasis",
  },
  mal: {
    french: "mal",
    english: "badly / bad",
    type: "adverb",
    example: "il parle mal (he speaks badly)",
    note: "opposite of 'bien'",
  },
};

// Verb aimer (to like/love) conjugations
export const aimerConjugations = {
  je: {
    pronoun: "je",
    conjugation: "aime",
    combined: "j'aime",
    english: "I like / I love",
    englishFull: "I like / I love",
    note: "j' before vowel",
  },
  tu: {
    pronoun: "tu",
    conjugation: "aimes",
    combined: "tu aimes",
    english: "you like / you love (informal)",
    englishFull: "you like / you love (informal)",
  },
  il: {
    pronoun: "il",
    conjugation: "aime",
    combined: "il aime",
    english: "he likes / he loves",
    englishFull: "he likes / he loves",
  },
  elle: {
    pronoun: "elle",
    conjugation: "aime",
    combined: "elle aime",
    english: "she likes / she loves",
    englishFull: "she likes / she loves",
  },
  nous: {
    pronoun: "nous",
    conjugation: "aimons",
    combined: "nous aimons",
    english: "we like / we love",
    englishFull: "we like / we love",
  },
  vous: {
    pronoun: "vous",
    conjugation: "aimez",
    combined: "vous aimez",
    english: "you like / you love (formal/plural)",
    englishFull: "you like / you love (formal or plural)",
  },
  ils: {
    pronoun: "ils",
    conjugation: "aiment",
    combined: "ils aiment",
    english: "they like / they love (masculine)",
    englishFull: "they like / they love (masculine or mixed)",
  },
  elles: {
    pronoun: "elles",
    conjugation: "aiment",
    combined: "elles aiment",
    english: "they like / they love (feminine)",
    englishFull: "they like / they love (all feminine)",
  },
};

// Verb manger (to eat) conjugations
export const mangerConjugations = {
  je: {
    pronoun: "je",
    conjugation: "mange",
    combined: "je mange",
    english: "I eat",
    englishFull: "I eat / I am eating",
  },
  tu: {
    pronoun: "tu",
    conjugation: "manges",
    combined: "tu manges",
    english: "you eat (informal)",
    englishFull: "you eat / you are eating (informal)",
  },
  il: {
    pronoun: "il",
    conjugation: "mange",
    combined: "il mange",
    english: "he eats",
    englishFull: "he eats / he is eating",
  },
  elle: {
    pronoun: "elle",
    conjugation: "mange",
    combined: "elle mange",
    english: "she eats",
    englishFull: "she eats / she is eating",
  },
  nous: {
    pronoun: "nous",
    conjugation: "mangeons",
    combined: "nous mangeons",
    english: "we eat",
    englishFull: "we eat / we are eating",
    note: "note: mangeons not mangons",
  },
  vous: {
    pronoun: "vous",
    conjugation: "mangez",
    combined: "vous mangez",
    english: "you eat (formal/plural)",
    englishFull: "you eat / you are eating (formal or plural)",
  },
  ils: {
    pronoun: "ils",
    conjugation: "mangent",
    combined: "ils mangent",
    english: "they eat (masculine)",
    englishFull: "they eat / they are eating (masculine or mixed)",
  },
  elles: {
    pronoun: "elles",
    conjugation: "mangent",
    combined: "elles mangent",
    english: "they eat (feminine)",
    englishFull: "they eat / they are eating (all feminine)",
  },
};

// Verb boire (to drink) conjugations - IRREGULAR
export const boireConjugations = {
  je: {
    pronoun: "je",
    conjugation: "bois",
    combined: "je bois",
    english: "I drink",
    englishFull: "I drink / I am drinking",
    note: "boi- stem",
  },
  tu: {
    pronoun: "tu",
    conjugation: "bois",
    combined: "tu bois",
    english: "you drink (informal)",
    englishFull: "you drink / you are drinking (informal)",
    note: "boi- stem",
  },
  il: {
    pronoun: "il",
    conjugation: "boit",
    combined: "il boit",
    english: "he drinks",
    englishFull: "he drinks / he is drinking",
    note: "boi- stem + t",
  },
  elle: {
    pronoun: "elle",
    conjugation: "boit",
    combined: "elle boit",
    english: "she drinks",
    englishFull: "she drinks / she is drinking",
    note: "boi- stem + t",
  },
  nous: {
    pronoun: "nous",
    conjugation: "buvons",
    combined: "nous buvons",
    english: "we drink",
    englishFull: "we drink / we are drinking",
    note: "STEM CHANGE to buv-",
  },
  vous: {
    pronoun: "vous",
    conjugation: "buvez",
    combined: "vous buvez",
    english: "you drink (formal/plural)",
    englishFull: "you drink / you are drinking (formal or plural)",
    note: "buv- stem",
  },
  ils: {
    pronoun: "ils",
    conjugation: "boivent",
    combined: "ils boivent",
    english: "they drink (masculine)",
    englishFull: "they drink / they are drinking (masculine or mixed)",
    note: "back to boi- stem + vent",
  },
  elles: {
    pronoun: "elles",
    conjugation: "boivent",
    combined: "elles boivent",
    english: "they drink (feminine)",
    englishFull: "they drink / they are drinking (all feminine)",
    note: "boi- stem + vent",
  },
};

// Verb manger - Passé Composé (Past Tense)
export const mangerPasseComposeConjugations = {
  je: {
    pronoun: "je",
    auxiliary: "ai",
    pastParticiple: "mangé",
    combined: "j'ai mangé",
    english: "I ate / I have eaten",
    englishFull: "I ate / I have eaten",
    note: "passé composé - regular -ER past participle",
  },
  tu: {
    pronoun: "tu",
    auxiliary: "as",
    pastParticiple: "mangé",
    combined: "tu as mangé",
    english: "you ate (informal)",
    englishFull: "you ate / you have eaten (informal)",
    note: "passé composé",
  },
  il: {
    pronoun: "il",
    auxiliary: "a",
    pastParticiple: "mangé",
    combined: "il a mangé",
    english: "he ate",
    englishFull: "he ate / he has eaten",
    note: "passé composé",
  },
  elle: {
    pronoun: "elle",
    auxiliary: "a",
    pastParticiple: "mangé",
    combined: "elle a mangé",
    english: "she ate",
    englishFull: "she ate / she has eaten",
    note: "passé composé",
  },
  nous: {
    pronoun: "nous",
    auxiliary: "avons",
    pastParticiple: "mangé",
    combined: "nous avons mangé",
    english: "we ate",
    englishFull: "we ate / we have eaten",
    note: "passé composé",
  },
  vous: {
    pronoun: "vous",
    auxiliary: "avez",
    pastParticiple: "mangé",
    combined: "vous avez mangé",
    english: "you ate (formal/plural)",
    englishFull: "you ate / you have eaten (formal or plural)",
    note: "passé composé",
  },
  ils: {
    pronoun: "ils",
    auxiliary: "ont",
    pastParticiple: "mangé",
    combined: "ils ont mangé",
    english: "they ate (masculine)",
    englishFull: "they ate / they have eaten (masculine or mixed)",
    note: "passé composé",
  },
  elles: {
    pronoun: "elles",
    auxiliary: "ont",
    pastParticiple: "mangé",
    combined: "elles ont mangé",
    english: "they ate (feminine)",
    englishFull: "they ate / they have eaten (all feminine)",
    note: "passé composé",
  },
};

// Verb boire - Passé Composé (Past Tense) - IRREGULAR
export const boirePasseComposeConjugations = {
  je: {
    pronoun: "je",
    auxiliary: "ai",
    pastParticiple: "bu",
    combined: "j'ai bu",
    english: "I drank / I have drunk",
    englishFull: "I drank / I have drunk",
    note: "passé composé - IRREGULAR past participle: bu",
  },
  tu: {
    pronoun: "tu",
    auxiliary: "as",
    pastParticiple: "bu",
    combined: "tu as bu",
    english: "you drank (informal)",
    englishFull: "you drank / you have drunk (informal)",
    note: "passé composé",
  },
  il: {
    pronoun: "il",
    auxiliary: "a",
    pastParticiple: "bu",
    combined: "il a bu",
    english: "he drank",
    englishFull: "he drank / he has drunk",
    note: "passé composé",
  },
  elle: {
    pronoun: "elle",
    auxiliary: "a",
    pastParticiple: "bu",
    combined: "elle a bu",
    english: "she drank",
    englishFull: "she drank / she has drunk",
    note: "passé composé",
  },
  nous: {
    pronoun: "nous",
    auxiliary: "avons",
    pastParticiple: "bu",
    combined: "nous avons bu",
    english: "we drank",
    englishFull: "we drank / we have drunk",
    note: "passé composé",
  },
  vous: {
    pronoun: "vous",
    auxiliary: "avez",
    pastParticiple: "bu",
    combined: "vous avez bu",
    english: "you drank (formal/plural)",
    englishFull: "you drank / you have drunk (formal or plural)",
    note: "passé composé",
  },
  ils: {
    pronoun: "ils",
    auxiliary: "ont",
    pastParticiple: "bu",
    combined: "ils ont bu",
    english: "they drank (masculine)",
    englishFull: "they drank / they have drunk (masculine or mixed)",
    note: "passé composé",
  },
  elles: {
    pronoun: "elles",
    auxiliary: "ont",
    pastParticiple: "bu",
    combined: "elles ont bu",
    english: "they drank (feminine)",
    englishFull: "they drank / they have drunk (all feminine)",
    note: "passé composé",
  },
};

// Verb être - Past Tense (Imperfect / Imparfait)
export const etrePastConjugations = {
  je: {
    pronoun: "je",
    conjugation: "étais",
    combined: "j'étais",
    english: "I was",
    englishFull: "I was",
    note: "imperfect tense",
  },
  tu: {
    pronoun: "tu",
    conjugation: "étais",
    combined: "tu étais",
    english: "you were (informal)",
    englishFull: "you were (informal)",
    note: "sounds same as j'étais",
  },
  il: {
    pronoun: "il",
    conjugation: "était",
    combined: "il était",
    english: "he was",
    englishFull: "he was",
    note: "similar sound to étais",
  },
  elle: {
    pronoun: "elle",
    conjugation: "était",
    combined: "elle était",
    english: "she was",
    englishFull: "she was",
    note: "similar sound to étais",
  },
  nous: {
    pronoun: "nous",
    conjugation: "étions",
    combined: "nous étions",
    english: "we were",
    englishFull: "we were",
    note: "imperfect tense",
  },
  vous: {
    pronoun: "vous",
    conjugation: "étiez",
    combined: "vous étiez",
    english: "you were (formal/plural)",
    englishFull: "you were (formal or plural)",
    note: "imperfect tense",
  },
  ils: {
    pronoun: "ils",
    conjugation: "étaient",
    combined: "ils étaient",
    english: "they were (masculine)",
    englishFull: "they were (masculine or mixed)",
    note: "sounds like 'étè'",
  },
  elles: {
    pronoun: "elles",
    conjugation: "étaient",
    combined: "elles étaient",
    english: "they were (feminine)",
    englishFull: "they were (all feminine)",
    note: "sounds like 'étè'",
  },
};

// Verb avoir - Past Tense (Imperfect / Imparfait)
export const avoirPastConjugations = {
  je: {
    pronoun: "je",
    conjugation: "avais",
    combined: "j'avais",
    english: "I had",
    englishFull: "I had",
    note: "imperfect tense",
  },
  tu: {
    pronoun: "tu",
    conjugation: "avais",
    combined: "tu avais",
    english: "you had (informal)",
    englishFull: "you had (informal)",
    note: "sounds same as j'avais",
  },
  il: {
    pronoun: "il",
    conjugation: "avait",
    combined: "il avait",
    english: "he had",
    englishFull: "he had",
    note: "slightly different pronunciation",
  },
  elle: {
    pronoun: "elle",
    conjugation: "avait",
    combined: "elle avait",
    english: "she had",
    englishFull: "she had",
    note: "slightly different pronunciation",
  },
  nous: {
    pronoun: "nous",
    conjugation: "avions",
    combined: "nous avions",
    english: "we had",
    englishFull: "we had",
    note: "imperfect tense",
  },
  vous: {
    pronoun: "vous",
    conjugation: "aviez",
    combined: "vous aviez",
    english: "you had (formal/plural)",
    englishFull: "you had (formal or plural)",
    note: "imperfect tense",
  },
  ils: {
    pronoun: "ils",
    conjugation: "avaient",
    combined: "ils avaient",
    english: "they had (masculine)",
    englishFull: "they had (masculine or mixed)",
    note: "sounds like 'avè'",
  },
  elles: {
    pronoun: "elles",
    conjugation: "avaient",
    combined: "elles avaient",
    english: "they had (feminine)",
    englishFull: "they had (all feminine)",
    note: "sounds like 'avè'",
  },
};

// Conditional Forms - devoir (should)
export const devoirConditionalConjugations = {
  je: {
    pronoun: "je",
    conjugation: "devrais",
    combined: "je devrais",
    english: "I should",
    englishFull: "I should / I ought to",
    note: "conditional mood",
  },
  tu: {
    pronoun: "tu",
    conjugation: "devrais",
    combined: "tu devrais",
    english: "you should (informal)",
    englishFull: "you should / you ought to (informal)",
    note: "conditional mood",
  },
  il: {
    pronoun: "il",
    conjugation: "devrait",
    combined: "il devrait",
    english: "he should",
    englishFull: "he should / he ought to",
    note: "conditional mood",
  },
  elle: {
    pronoun: "elle",
    conjugation: "devrait",
    combined: "elle devrait",
    english: "she should",
    englishFull: "she should / she ought to",
    note: "conditional mood",
  },
  nous: {
    pronoun: "nous",
    conjugation: "devrions",
    combined: "nous devrions",
    english: "we should",
    englishFull: "we should / we ought to",
    note: "conditional mood",
  },
  vous: {
    pronoun: "vous",
    conjugation: "devriez",
    combined: "vous devriez",
    english: "you should (formal/plural)",
    englishFull: "you should / you ought to (formal or plural)",
    note: "conditional mood",
  },
  ils: {
    pronoun: "ils",
    conjugation: "devraient",
    combined: "ils devraient",
    english: "they should (masculine)",
    englishFull: "they should / they ought to (masculine or mixed)",
    note: "conditional mood",
  },
  elles: {
    pronoun: "elles",
    conjugation: "devraient",
    combined: "elles devraient",
    english: "they should (feminine)",
    englishFull: "they should / they ought to (all feminine)",
    note: "conditional mood",
  },
};

// Conditional Forms - pouvoir (could)
export const pouvoirConditionalConjugations = {
  je: {
    pronoun: "je",
    conjugation: "pourrais",
    combined: "je pourrais",
    english: "I could",
    englishFull: "I could / I would be able to",
    note: "conditional mood",
  },
  tu: {
    pronoun: "tu",
    conjugation: "pourrais",
    combined: "tu pourrais",
    english: "you could (informal)",
    englishFull: "you could / you would be able to (informal)",
    note: "conditional mood",
  },
  il: {
    pronoun: "il",
    conjugation: "pourrait",
    combined: "il pourrait",
    english: "he could",
    englishFull: "he could / he would be able to",
    note: "conditional mood",
  },
  elle: {
    pronoun: "elle",
    conjugation: "pourrait",
    combined: "elle pourrait",
    english: "she could",
    englishFull: "she could / she would be able to",
    note: "conditional mood",
  },
  nous: {
    pronoun: "nous",
    conjugation: "pourrions",
    combined: "nous pourrions",
    english: "we could",
    englishFull: "we could / we would be able to",
    note: "conditional mood",
  },
  vous: {
    pronoun: "vous",
    conjugation: "pourriez",
    combined: "vous pourriez",
    english: "you could (formal/plural)",
    englishFull: "you could / you would be able to (formal or plural)",
    note: "conditional mood",
  },
  ils: {
    pronoun: "ils",
    conjugation: "pourraient",
    combined: "ils pourraient",
    english: "they could (masculine)",
    englishFull: "they could / they would be able to (masculine or mixed)",
    note: "conditional mood",
  },
  elles: {
    pronoun: "elles",
    conjugation: "pourraient",
    combined: "elles pourraient",
    english: "they could (feminine)",
    englishFull: "they could / they would be able to (all feminine)",
    note: "conditional mood",
  },
};

// Conditional Forms - vouloir (would like)
export const vouloirConditionalConjugations = {
  je: {
    pronoun: "je",
    conjugation: "voudrais",
    combined: "je voudrais",
    english: "I would like",
    englishFull: "I would like / I would want",
    note: "conditional mood - polite!",
  },
  tu: {
    pronoun: "tu",
    conjugation: "voudrais",
    combined: "tu voudrais",
    english: "you would like (informal)",
    englishFull: "you would like / you would want (informal)",
    note: "conditional mood",
  },
  il: {
    pronoun: "il",
    conjugation: "voudrait",
    combined: "il voudrait",
    english: "he would like",
    englishFull: "he would like / he would want",
    note: "conditional mood",
  },
  elle: {
    pronoun: "elle",
    conjugation: "voudrait",
    combined: "elle voudrait",
    english: "she would like",
    englishFull: "she would like / she would want",
    note: "conditional mood",
  },
  nous: {
    pronoun: "nous",
    conjugation: "voudrions",
    combined: "nous voudrions",
    english: "we would like",
    englishFull: "we would like / we would want",
    note: "conditional mood",
  },
  vous: {
    pronoun: "vous",
    conjugation: "voudriez",
    combined: "vous voudriez",
    english: "you would like (formal/plural)",
    englishFull: "you would like / you would want (formal or plural)",
    note: "conditional mood",
  },
  ils: {
    pronoun: "ils",
    conjugation: "voudraient",
    combined: "ils voudraient",
    english: "they would like (masculine)",
    englishFull: "they would like / they would want (masculine or mixed)",
    note: "conditional mood",
  },
  elles: {
    pronoun: "elles",
    conjugation: "voudraient",
    combined: "elles voudraient",
    english: "they would like (feminine)",
    englishFull: "they would like / they would want (all feminine)",
    note: "conditional mood",
  },
};

// Conditional Forms - aller (would go)
export const allerConditionalConjugations = {
  je: {
    pronoun: "je",
    conjugation: "irais",
    combined: "j'irais",
    english: "I would go",
    englishFull: "I would go",
    note: "conditional mood",
  },
  tu: {
    pronoun: "tu",
    conjugation: "irais",
    combined: "tu irais",
    english: "you would go (informal)",
    englishFull: "you would go (informal)",
    note: "conditional mood",
  },
  il: {
    pronoun: "il",
    conjugation: "irait",
    combined: "il irait",
    english: "he would go",
    englishFull: "he would go",
    note: "conditional mood",
  },
  elle: {
    pronoun: "elle",
    conjugation: "irait",
    combined: "elle irait",
    english: "she would go",
    englishFull: "she would go",
    note: "conditional mood",
  },
  nous: {
    pronoun: "nous",
    conjugation: "irions",
    combined: "nous irions",
    english: "we would go",
    englishFull: "we would go",
    note: "conditional mood",
  },
  vous: {
    pronoun: "vous",
    conjugation: "iriez",
    combined: "vous iriez",
    english: "you would go (formal/plural)",
    englishFull: "you would go (formal or plural)",
    note: "conditional mood",
  },
  ils: {
    pronoun: "ils",
    conjugation: "iraient",
    combined: "ils iraient",
    english: "they would go (masculine)",
    englishFull: "they would go (masculine or mixed)",
    note: "conditional mood",
  },
  elles: {
    pronoun: "elles",
    conjugation: "iraient",
    combined: "elles iraient",
    english: "they would go (feminine)",
    englishFull: "they would go (all feminine)",
    note: "conditional mood",
  },
};

// Conditional Forms - faire (would do)
export const faireConditionalConjugations = {
  je: {
    pronoun: "je",
    conjugation: "ferais",
    combined: "je ferais",
    english: "I would do",
    englishFull: "I would do / I would make",
    note: "conditional mood",
  },
  tu: {
    pronoun: "tu",
    conjugation: "ferais",
    combined: "tu ferais",
    english: "you would do (informal)",
    englishFull: "you would do / you would make (informal)",
    note: "conditional mood",
  },
  il: {
    pronoun: "il",
    conjugation: "ferait",
    combined: "il ferait",
    english: "he would do",
    englishFull: "he would do / he would make",
    note: "conditional mood",
  },
  elle: {
    pronoun: "elle",
    conjugation: "ferait",
    combined: "elle ferait",
    english: "she would do",
    englishFull: "she would do / she would make",
    note: "conditional mood",
  },
  nous: {
    pronoun: "nous",
    conjugation: "ferions",
    combined: "nous ferions",
    english: "we would do",
    englishFull: "we would do / we would make",
    note: "conditional mood",
  },
  vous: {
    pronoun: "vous",
    conjugation: "feriez",
    combined: "vous feriez",
    english: "you would do (formal/plural)",
    englishFull: "you would do / you would make (formal or plural)",
    note: "conditional mood",
  },
  ils: {
    pronoun: "ils",
    conjugation: "feraient",
    combined: "ils feraient",
    english: "they would do (masculine)",
    englishFull: "they would do / they would make (masculine or mixed)",
    note: "conditional mood",
  },
  elles: {
    pronoun: "elles",
    conjugation: "feraient",
    combined: "elles feraient",
    english: "they would do (feminine)",
    englishFull: "they would do / they would make (all feminine)",
    note: "conditional mood",
  },
};

// Unit 7: Knowledge & Learning Verbs

// comprendre (to understand) - follows prendre pattern
export const comprendreConjugations = {
  je: {
    pronoun: "je",
    conjugation: "comprends",
    combined: "je comprends",
    english: "I understand",
    englishFull: "I understand",
    note: "same pattern as prendre",
  },
  tu: {
    pronoun: "tu",
    conjugation: "comprends",
    combined: "tu comprends",
    english: "you understand (informal)",
    englishFull: "you understand (informal)",
    note: "Tu comprends?",
  },
  il: {
    pronoun: "il",
    conjugation: "comprend",
    combined: "il comprend",
    english: "he understands",
    englishFull: "he understands",
    note: "no final -s or -t",
  },
  elle: {
    pronoun: "elle",
    conjugation: "comprend",
    combined: "elle comprend",
    english: "she understands",
    englishFull: "she understands",
    note: "same as il",
  },
  nous: {
    pronoun: "nous",
    conjugation: "comprenons",
    combined: "nous comprenons",
    english: "we understand",
    englishFull: "we understand",
    note: "add -ons",
  },
  vous: {
    pronoun: "vous",
    conjugation: "comprenez",
    combined: "vous comprenez",
    english: "you understand (formal/plural)",
    englishFull: "you understand (formal or plural)",
    note: "polite form",
  },
  ils: {
    pronoun: "ils",
    conjugation: "comprennent",
    combined: "ils comprennent",
    english: "they understand (masculine)",
    englishFull: "they understand (masculine or mixed)",
    note: "double n, silent -ent",
  },
  elles: {
    pronoun: "elles",
    conjugation: "comprennent",
    combined: "elles comprennent",
    english: "they understand (feminine)",
    englishFull: "they understand (all feminine)",
    note: "double n, silent -ent",
  },
};

// penser (to think) - regular -ER verb
export const penserConjugations = {
  je: {
    pronoun: "je",
    conjugation: "pense",
    combined: "je pense",
    english: "I think",
    englishFull: "I think",
    note: "regular -ER verb",
  },
  tu: {
    pronoun: "tu",
    conjugation: "penses",
    combined: "tu penses",
    english: "you think (informal)",
    englishFull: "you think (informal)",
    note: "regular -es ending",
  },
  il: {
    pronoun: "il",
    conjugation: "pense",
    combined: "il pense",
    english: "he thinks",
    englishFull: "he thinks",
    note: "regular -e ending",
  },
  elle: {
    pronoun: "elle",
    conjugation: "pense",
    combined: "elle pense",
    english: "she thinks",
    englishFull: "she thinks",
    note: "same as il",
  },
  nous: {
    pronoun: "nous",
    conjugation: "pensons",
    combined: "nous pensons",
    english: "we think",
    englishFull: "we think",
    note: "regular -ons",
  },
  vous: {
    pronoun: "vous",
    conjugation: "pensez",
    combined: "vous pensez",
    english: "you think (formal/plural)",
    englishFull: "you think (formal or plural)",
    note: "regular -ez",
  },
  ils: {
    pronoun: "ils",
    conjugation: "pensent",
    combined: "ils pensent",
    english: "they think (masculine)",
    englishFull: "they think (masculine or mixed)",
    note: "silent -ent",
  },
  elles: {
    pronoun: "elles",
    conjugation: "pensent",
    combined: "elles pensent",
    english: "they think (feminine)",
    englishFull: "they think (all feminine)",
    note: "silent -ent",
  },
};

// savoir (to know facts/skills) - irregular, rank 21!
export const savoirConjugations = {
  je: {
    pronoun: "je",
    conjugation: "sais",
    combined: "je sais",
    english: "I know",
    englishFull: "I know",
    note: "⭐ je ne sais pas = most common phrase!",
  },
  tu: {
    pronoun: "tu",
    conjugation: "sais",
    combined: "tu sais",
    english: "you know (informal)",
    englishFull: "you know (informal)",
    note: "Tu sais?",
  },
  il: {
    pronoun: "il",
    conjugation: "sait",
    combined: "il sait",
    english: "he knows",
    englishFull: "he knows",
    note: "silent -t",
  },
  elle: {
    pronoun: "elle",
    conjugation: "sait",
    combined: "elle sait",
    english: "she knows",
    englishFull: "she knows",
    note: "silent -t",
  },
  nous: {
    pronoun: "nous",
    conjugation: "savons",
    combined: "nous savons",
    english: "we know",
    englishFull: "we know",
    note: "pronounced 'sa-von'",
  },
  vous: {
    pronoun: "vous",
    conjugation: "savez",
    combined: "vous savez",
    english: "you know (formal/plural)",
    englishFull: "you know (formal or plural)",
    note: "pronounced 'sa-vay'",
  },
  ils: {
    pronoun: "ils",
    conjugation: "savent",
    combined: "ils savent",
    english: "they know (masculine)",
    englishFull: "they know (masculine or mixed)",
    note: "silent -ent",
  },
  elles: {
    pronoun: "elles",
    conjugation: "savent",
    combined: "elles savent",
    english: "they know (feminine)",
    englishFull: "they know (all feminine)",
    note: "silent -ent",
  },
};

// connaître (to know people/places) - irregular, rank 62
export const connaitreConjugations = {
  je: {
    pronoun: "je",
    conjugation: "connais",
    combined: "je connais",
    english: "I know",
    englishFull: "I know (people/places)",
    note: "for people and places only",
  },
  tu: {
    pronoun: "tu",
    conjugation: "connais",
    combined: "tu connais",
    english: "you know (informal)",
    englishFull: "you know (informal)",
    note: "Tu connais Marie?",
  },
  il: {
    pronoun: "il",
    conjugation: "connaît",
    combined: "il connaît",
    english: "he knows",
    englishFull: "he knows",
    note: "⚠️ circumflex accent î",
  },
  elle: {
    pronoun: "elle",
    conjugation: "connaît",
    combined: "elle connaît",
    english: "she knows",
    englishFull: "she knows",
    note: "circumflex accent î",
  },
  nous: {
    pronoun: "nous",
    conjugation: "connaissons",
    combined: "nous connaissons",
    english: "we know",
    englishFull: "we know",
    note: "double -ss-",
  },
  vous: {
    pronoun: "vous",
    conjugation: "connaissez",
    combined: "vous connaissez",
    english: "you know (formal/plural)",
    englishFull: "you know (formal or plural)",
    note: "double -ss-",
  },
  ils: {
    pronoun: "ils",
    conjugation: "connaissent",
    combined: "ils connaissent",
    english: "they know (masculine)",
    englishFull: "they know (masculine or mixed)",
    note: "double -ss-, silent -ent",
  },
  elles: {
    pronoun: "elles",
    conjugation: "connaissent",
    combined: "elles connaissent",
    english: "they know (feminine)",
    englishFull: "they know (all feminine)",
    note: "double -ss-, silent -ent",
  },
};

// croire (to believe) - irregular, rank 60
export const croireConjugations = {
  je: {
    pronoun: "je",
    conjugation: "crois",
    combined: "je crois",
    english: "I believe / I think",
    englishFull: "I believe / I think",
    note: "pronounced 'krwa'",
  },
  tu: {
    pronoun: "tu",
    conjugation: "crois",
    combined: "tu crois",
    english: "you believe (informal)",
    englishFull: "you believe / you think (informal)",
    note: "Tu crois?",
  },
  il: {
    pronoun: "il",
    conjugation: "croit",
    combined: "il croit",
    english: "he believes",
    englishFull: "he believes / he thinks",
    note: "silent -t",
  },
  elle: {
    pronoun: "elle",
    conjugation: "croit",
    combined: "elle croit",
    english: "she believes",
    englishFull: "she believes / she thinks",
    note: "silent -t",
  },
  nous: {
    pronoun: "nous",
    conjugation: "croyons",
    combined: "nous croyons",
    english: "we believe",
    englishFull: "we believe / we think",
    note: "y sound - 'krwa-yon'",
  },
  vous: {
    pronoun: "vous",
    conjugation: "croyez",
    combined: "vous croyez",
    english: "you believe (formal/plural)",
    englishFull: "you believe / you think (formal or plural)",
    note: "y sound - 'krwa-yay'",
  },
  ils: {
    pronoun: "ils",
    conjugation: "croient",
    combined: "ils croient",
    english: "they believe (masculine)",
    englishFull: "they believe / they think (masculine or mixed)",
    note: "silent -ent",
  },
  elles: {
    pronoun: "elles",
    conjugation: "croient",
    combined: "elles croient",
    english: "they believe (feminine)",
    englishFull: "they believe / they think (all feminine)",
    note: "silent -ent",
  },
};

// Food & Drink Nouns - Essential everyday vocabulary
export const foodNouns = {
  // Drinks
  eau: {
    french: "l'eau",
    english: "water",
    gender: "feminine",
    article: "l'eau",
    note: "feminine, vowel start",
  },
  cafe: {
    french: "le café",
    english: "coffee",
    gender: "masculine",
    article: "le café / un café",
    note: "very common!",
  },
  express: {
    french: "un express",
    english: "espresso",
    gender: "masculine",
    article: "un express",
    note: "short strong coffee",
  },
  the: {
    french: "le thé",
    english: "tea",
    gender: "masculine",
    article: "le thé / un thé",
  },
  lait: {
    french: "le lait",
    english: "milk",
    gender: "masculine",
    article: "le lait / du lait",
  },
  vin: {
    french: "le vin",
    english: "wine",
    gender: "masculine",
    article: "le vin / du vin",
  },
  biere: {
    french: "la bière",
    english: "beer",
    gender: "feminine",
    article: "la bière / une bière",
  },
  jus: {
    french: "le jus",
    english: "juice",
    gender: "masculine",
    article: "le jus / du jus",
  },
  // Bread & Basics
  pain: {
    french: "le pain",
    english: "bread",
    gender: "masculine",
    article: "le pain / du pain",
    note: "essential!",
  },
  baguette: {
    french: "une baguette",
    english: "baguette",
    gender: "feminine",
    article: "une baguette / la baguette",
    note: "iconic French bread!",
  },
  croissant: {
    french: "un croissant",
    english: "croissant",
    gender: "masculine",
    article: "un croissant / le croissant",
    note: "classic breakfast!",
  },
  beurre: {
    french: "le beurre",
    english: "butter",
    gender: "masculine",
    article: "le beurre / du beurre",
  },
  fromage: {
    french: "le fromage",
    english: "cheese",
    gender: "masculine",
    article: "le fromage / du fromage",
  },
  pizza: {
    french: "la pizza",
    english: "pizza",
    gender: "feminine",
    article: "la pizza / une pizza",
  },
  sel: {
    french: "le sel",
    english: "salt",
    gender: "masculine",
    article: "le sel / du sel",
  },
  poivre: {
    french: "le poivre",
    english: "pepper",
    gender: "masculine",
    article: "le poivre / du poivre",
  },
  sucre: {
    french: "le sucre",
    english: "sugar",
    gender: "masculine",
    article: "le sucre / du sucre",
  },
  // Proteins
  viande: {
    french: "la viande",
    english: "meat",
    gender: "feminine",
    article: "la viande / de la viande",
  },
  poulet: {
    french: "le poulet",
    english: "chicken",
    gender: "masculine",
    article: "le poulet / du poulet",
  },
  poisson: {
    french: "le poisson",
    english: "fish",
    gender: "masculine",
    article: "le poisson / du poisson",
  },
  boeuf: {
    french: "le bœuf",
    english: "beef",
    gender: "masculine",
    article: "le bœuf / du bœuf",
  },
  porc: {
    french: "le porc",
    english: "pork",
    gender: "masculine",
    article: "le porc / du porc",
  },
  oeufs: {
    french: "les œufs",
    english: "eggs",
    gender: "masculine",
    article: "les œufs / des œufs",
    note: "plural",
  },
  // Vegetables
  legumes: {
    french: "les légumes",
    english: "vegetables",
    gender: "masculine",
    article: "les légumes / des légumes",
    note: "plural",
  },
  salade: {
    french: "la salade",
    english: "salad / lettuce",
    gender: "feminine",
    article: "la salade / une salade",
  },
  tomate: {
    french: "la tomate",
    english: "tomato",
    gender: "feminine",
    article: "la tomate / une tomate",
  },
  pommeDeTerre: {
    french: "la pomme de terre",
    english: "potato",
    gender: "feminine",
    article: "une pomme de terre",
    note: "literally 'apple of earth'",
  },
  frites: {
    french: "les frites",
    english: "fries",
    gender: "feminine",
    article: "les frites / des frites",
    note: "plural",
  },
  haricots: {
    french: "les haricots",
    english: "beans",
    gender: "masculine",
    article: "les haricots / des haricots",
    note: "plural",
  },
  // Fruits
  fruits: {
    french: "les fruits",
    english: "fruits",
    gender: "masculine",
    article: "les fruits / des fruits",
    note: "plural",
  },
  pomme: {
    french: "la pomme",
    english: "apple",
    gender: "feminine",
    article: "la pomme / une pomme",
  },
  banane: {
    french: "la banane",
    english: "banana",
    gender: "feminine",
    article: "la banane / une banane",
  },
  orange: {
    french: "l'orange",
    english: "orange",
    gender: "feminine",
    article: "l'orange / une orange",
  },
  // Carbs
  riz: {
    french: "le riz",
    english: "rice",
    gender: "masculine",
    article: "le riz / du riz",
  },
  pates: {
    french: "les pâtes",
    english: "pasta",
    gender: "feminine",
    article: "les pâtes / des pâtes",
    note: "plural",
  },
  // Desserts
  gateau: {
    french: "le gâteau",
    english: "cake",
    gender: "masculine",
    article: "le gâteau / un gâteau",
  },
  glace: {
    french: "la glace",
    english: "ice cream",
    gender: "feminine",
    article: "la glace / de la glace",
  },
  chocolat: {
    french: "le chocolat",
    english: "chocolate",
    gender: "masculine",
    article: "le chocolat / du chocolat",
  },
};

// Slang & Informal Expressions
export const slangExpressions = {
  // France
  ouf: {
    french: "c'est ouf",
    english: "it's crazy/insane",
    region: "France",
    type: "verlan",
    note: "verlan (reversed) for 'fou'",
  },
  chelou: {
    french: "c'est chelou",
    english: "it's weird/sketchy",
    region: "France",
    type: "verlan",
    note: "verlan for 'louche'",
  },
  genial: {
    french: "c'est génial",
    english: "it's awesome/great",
    region: "France",
    type: "slang",
    note: "very common!",
  },
  nul: {
    french: "c'est nul",
    english: "it sucks/it's lame",
    region: "France",
    type: "slang",
    note: "negative",
  },
  cool: {
    french: "c'est cool",
    english: "it's cool",
    region: "France",
    type: "borrowed",
    note: "from English",
  },
  dingue: {
    french: "c'est dingue",
    english: "it's crazy/wild",
    region: "France",
    type: "slang",
  },
  vachement: {
    french: "vachement",
    english: "really/very",
    region: "France",
    type: "slang",
    example: "c'est vachement bon",
  },
  hyper: {
    french: "hyper",
    english: "super/really",
    region: "France",
    type: "slang",
    example: "c'est hyper bon",
  },
  mortel: {
    french: "c'est mortel",
    english: "it's deadly/awesome",
    region: "France",
    type: "slang",
    note: "positive meaning!",
  },
  // Quebec
  malade: {
    french: "c'est malade",
    english: "it's sick/awesome",
    region: "Quebec",
    type: "slang",
    note: "positive meaning!",
  },
  capot: {
    french: "c'est capot",
    english: "it's crazy/nuts",
    region: "Quebec",
    type: "slang",
  },
  ecoeruant: {
    french: "c'est écœurant",
    english: "it's disgusting/amazing",
    region: "Quebec",
    type: "slang",
    note: "can be positive OR negative!",
  },
  leFun: {
    french: "c'est le fun",
    english: "it's fun",
    region: "Quebec",
    type: "borrowed",
    note: "from English",
  },
  poche: {
    french: "c'est poche",
    english: "it sucks/it's bad",
    region: "Quebec",
    type: "slang",
    note: "negative",
  },
  benCorrect: {
    french: "c'est ben correct",
    english: "it's really good/fine",
    region: "Quebec",
    type: "slang",
    note: "'ben' = 'bien' in Quebec",
  },
  // Africa
  gnama: {
    french: "c'est gnama",
    english: "it's good/tasty",
    region: "West Africa",
    type: "slang",
    note: "Senegal, Ivory Coast",
  },
  grave: {
    french: "c'est grave",
    english: "it's serious/intense",
    region: "Africa & France",
    type: "slang",
    note: "used for emphasis",
  },
  chaud: {
    french: "c'est chaud",
    english: "it's hot/difficult/intense",
    region: "Africa & France",
    type: "slang",
    note: "figurative meaning",
  },
  fort: {
    french: "c'est fort",
    english: "it's strong/intense",
    region: "Africa",
    type: "slang",
  },
  // Universal
  top: {
    french: "c'est top",
    english: "it's top/the best",
    region: "Universal",
    type: "borrowed",
    note: "from English",
  },
};

export function getWrongAnswerHint(correctAnswer, userAnswer, category) {
  // For pronouns
  if (category === "pronoun" && pronouns[userAnswer]) {
    const wrongPronoun = pronouns[userAnswer];
    return `That's "${wrongPronoun.english}", not "${pronouns[correctAnswer]?.english}"`;
  }

  // For conjugations
  if (category === "conjugation") {
    return `Check your conjugation - the answer should be "${correctAnswer}"`;
  }

  return `Incorrect - expected "${correctAnswer}"`;
}
