/**
 * Reading Passage Vocabulary
 * Word translations for interactive reading tooltips
 * Extracted and deduplicated from ReadingPassage.jsx
 * Contains 2469 unique translations
 * ALPHABETICALLY SORTED
 */

export const readingVocabulary = {
  "-": "-",
  "- un": "- a",
  "- un très": "- a very",
  "- un très bon": "- a very good",
  '"Amélie"': '"Amélie"',
  '"Amélie" -': '"Amélie" -',
  '"Bonjour!': '"Hello!',
  "\"C'est": "\"That's / \"It's",
  '"Je': '"I',
  '"Quelle': '"What',
  '"Quelle surprise!"': '"What a surprise!"',
  '"Salut': '"Hi',
  "10h": "10 o'clock / 10pm",
  "10h.": "10pm.",
  "8h": "8 o'clock",
  "9h": "9 o'clock / 9pm",
  "9h pour": "9pm to",
  a: "has / have / to / at",
  à: "to / at / in",
  À: "To / At",
  "à 8h": "at 8am",
  "à 8h.": "at 8am.",
  "à Bordeaux": "in Bordeaux / to Bordeaux",
  "a bu": "drank",
  "À cause": "Because",
  "à cause du": "because of the",
  "À cause du": "Because of the",
  "à cause du temps": "because of time",
  "à cette": "to this",
  "à cette rencontre": "to this meeting",
  "a commencé": "started / has started",
  "à côté": "next to / beside",
  "à côté de": "next to",
  "à côté des": "next to the",
  "a dit": "said",
  "à dix": "at ten / ten",
  "à dix minutes": "ten minutes away",
  "a dû": "had to",
  "a dû partir": "had to leave",
  "a dû partir vers": "had to leave around",
  "à l'université": "at university / at the university",
  "à la": "at the / to the",
  "à la Sorbonne": "at the Sorbonne",
  "à la sorbonne": "at the Sorbonne",
  "à la Sorbonne parce": "at the Sorbonne because",
  "à Lyon": "in Lyon / to Lyon",
  "à Lyon.": "to Lyon.",
  "à ma": "to my / at my",
  "à ma journée": "about my day",
  "à ma sortie": "to my outing",
  "a mangé": "ate",
  "à mes": "to my / at my",
  "à mes rêves": "about my dreams",
  "à Montmartre": "in Montmartre",
  "à neuf heures": "at nine o'clock",
  "à Nice": "in Nice / to Nice",
  "à notre table": "to our table",
  "à Paris": "in Paris / to Paris",
  'à Paris!"': 'in Paris!"',
  "a parlé": "spoke",
  "à parler": "to talk / to speak",
  "à sept heures": "at seven o'clock",
  "a vus": "saw",
  "a-t-il": "does he have",
  achèterais: "would buy",
  activement: "actively",
  addition: "bill/check",
  admirer: "to admire",
  adorent: "love / adore (ils/elles)",
  ah: "ah",
  "ah oui": "oh yes",
  ai: "have",
  "ai besoin de": "need / have need of",
  "ai bu": "drank",
  "ai demandé": "asked / have asked",
  "ai dit": "said / have said",
  "ai dit que": "said that",
  "ai eu le": "had the",
  "ai eu le même": "had the same",
  "ai eu une": "had a",
  "ai eu une très": "had a very",
  "ai mangé": "ate",
  "ai pensé:": "thought:",
  "ai voulu": "wanted / have wanted",
  "ai vu": "saw / have seen",
  aident: "help",
  aider: "to help",
  aie: "have (subjunctive, je)",
  aies: "have (subjunctive, tu)",
  aimait: "liked / was liking",
  aime: "like / love",
  aimé: "liked / loved",
  "aime beaucoup": "really like / love a lot",
  "aime beaucoup ce": "really like this",
  "aime bien": "really like",
  "aime les": "love the",
  "aime les samedis": "love Saturdays",
  "aime les samedis à": "love Saturdays in",
  aiment: "like/love",
  aimer: "to like/love",
  aimerais: "would like",
  aimes: "like/love",
  aimez: "like/love",
  aimons: "like/love",
  allé: "gone (past participle of aller)",
  "allé près": "went near",
  "allé près du": "went near the",
  "allé vers lui": "went towards him",
  allée: "gone (feminine past participle of aller)",
  allées: "gone (feminine plural past participle of aller)",
  aller: "to go",
  "aller au café": "to go to the café",
  allés: "gone (masculine plural past participle of aller)",
  "allés au": "gone to",
  "allés au cinéma": "went to cinema",
  allez: "go",
  allons: "go",
  "allons avoir": "are going to have",
  "allons manger": "are going to eat",
  "allons partir": "are going to leave",
  "allons voir": "are going to see",
  "allons-y": "let's go!",
  alors: "so / then",
  Amélie: "Amélie (famous French film)",
  "Amélie.": "Amélie.",
  ami: "friend",
  "ami Pierre.": "friend Pierre.",
  amie: "friend (fem)",
  "amie de": "friend from",
  "amie de la": "friend from the",
  amis: "friends",
  "amis.": "friends.",
  amuse: "amuses / have fun",
  amuser: "to amuse",
  animal: "animal",
  animaux: "animals",
  année: "year",
  "année dernière": "last year",
  ans: "years",
  appeler: "to call",
  apprend: "learns",
  "apprend des mots": "learns words",
  "apprend des mots nouveaux": "learns new words",
  apprendre: "to learn",
  apprends: "learn (I/you)",
  apprenons: "learn (we)",
  apprentissage: "learning (process)",
  appris: "learned (past participle)",
  après: "after / afterwards",
  Après: "After",
  "Après le": "After the",
  "après le café": "after coffee",
  "après le film": "after the film",
  "Après le film": "After the film",
  "après les cours": "after classes",
  "après les cours je révise": "after classes I review",
  "après mon": "after my",
  "après mon café": "after my coffee",
  "après-midi": "afternoon",
  "après-midi,": "afternoon,",
  arbre: "tree",
  Arc: "Arc / Arch",
  argent: "money",
  arrivé: "arrived",
  arrivent: "arrive (ils/elles)",
  arriver: "to arrive",
  artiste: "artist",
  artistes: "artists",
  as: "have",
  "as besoin de": "need (you have need of)",
  "as bu": "drank",
  "as mangé": "ate",
  "as-tu": "do you have",
  assis: "sitting / seated",
  "assis sur un": "sitting on a",
  assise: "sitting / seated (fem)",
  attendent: "wait (ils/elles)",
  attire: "attracts",
  au: "to/at the (masc)",
  Au: "At / To",
  "au café": "to the café",
  "au Café de Flore": "to/at Café de Flore",
  "au café qui": "to the café that",
  "au cinéma": "to the cinema",
  "au Jardin": "to the Garden",
  "au Jardin des Tuileries": "at the Tuileries Garden",
  "au Jardin du": "to the Garden of",
  "au Jardin du Luxembourg": "to Jardin du Luxembourg",
  "au Jardin du Luxembourg près de": "to Jardin du Luxembourg near",
  "au loin": "in the distance",
  "au Louvre": "at the Louvre",
  "au parc": "to the park",
  "au restaurant": "at the restaurant",
  "Au restaurant": "At the restaurant",
  "au Restaurant Le Procope": "at Restaurant Le Procope",
  "au restaurant qui": "at the restaurant that",
  "Au restaurant,": "At the restaurant,",
  "au revoir": "goodbye",
  "au-delà": "beyond",
  Auguste: "Auguste (first name)",
  "Auguste Renoir": "Auguste Renoir",
  aujourd: "today",
  "aujourd'hui": "today",
  "aujourd'hui j'ai bien appris": "today I learned well",
  aussi: "also / too",
  autour: "around",
  "autour de": "around",
  "autour des": "around the",
  autre: "other / another",
  "autre ville": "another city",
  autres: "others/other",
  aux: "to/at the (plural)",
  "aux restaurants": "to the restaurants",
  avaient: "had",
  avais: "had",
  "avais faim": "was hungry",
  "avais raison": "were right",
  avait: "had / there was",
  "avait le": "had the / there was the",
  "avait le film": "had the film / there was the film",
  avant: "before",
  Avant: "Before",
  "avant de": "before (doing)",
  "Avant de": "Before",
  "avant de dormir": "before sleeping",
  "Avant de dormir,": "Before sleeping,",
  "avant de partir": "before leaving",
  "avant le café": "before coffee",
  "avant que": "before (someone does)",
  avec: "with",
  "avec le temps": "with time",
  "avec mes": "with my",
  "avec mes amis": "with my friends",
  "avec mes amis.": "with my friends.",
  "avec tes amis": "with your friends",
  avez: "have",
  "avez bu": "drank",
  "avez mangé": "ate",
  aviez: "had",
  avions: "had",
  "avions faim": "were hungry",
  "avions mangé": "had eaten",
  avoir: "to have",
  "avoir besoin de": "to need",
  "avoir.": "to have.",
  avons: "have",
  "avons beaucoup aimé": "really liked",
  "avons bu": "drank",
  "avons commandé": "ordered / have ordered",
  "avons commandé des": "ordered some",
  "avons décidé": "decided / have decided",
  "avons décidé d'aller": "decided to go",
  "avons décidé de": "decided to",
  "avons mangé": "ate / have eaten",
  "avons mangé de la": "ate some",
  "avons parlé": "talked / have talked",
  "avons parlé de": "talked about",
  "avons parlé de la": "talked about the",
  "avons pas vue": "haven't seen (her)",
  "avons pris": "had / have had / took",
  "avons pris un dernier": "had one last",
  "avons pu": "were able to / could",
  "avons pu être": "were able to be",
  "avons vu": "saw / have seen",
  "avons vu Marie": "saw Marie",
  baguette: "baguette",
  bah: "well (filler)",
  banane: "banana",
  banc: "bench",
  bayeux: "Bayeux - Medieval Norman town",
  Bayeux: "Bayeux (medieval Norman town)",
  beau: "nice / beautiful / handsome",
  "beau à Paris": "nice in Paris",
  "beau.": "nice.",
  beaucoup: "many / a lot / much",
  "beaucoup aimé": "really liked",
  "beaucoup ce parc": "this park a lot",
  "beaucoup de": "many / a lot of",
  "beaucoup de choses": "many things",
  "beaucoup de gens dans": "many people in",
  "beaucoup visitent": "many visit",
  beauté: "beauty",
  beaux: "beautiful (masc plural)",
  belle: "beautiful",
  "belle cathédrale": "beautiful cathedral",
  "belle journée": "beautiful day",
  belles: "beautiful (fem plural)",
  ben: "well (Quebec)",
  "ben correct": "really good (Quebec)",
  besoin: "need",
  beurre: "butter",
  bien: "well / good",
  "bien appris": "learned well",
  "bien maintenant": "well now",
  "bien sûr": "of course",
  bière: "beer",
  bleu: "blue",
  bœuf: "beef",
  boire: "to drink",
  bois: "drink",
  boit: "drinks",
  boivent: "drink",
  bon: "good",
  "bon et très": "good and very",
  "bon film": "good film",
  "bon film français": "good French film",
  bonjour: "hello",
  bonsoir: "good evening",
  Bonsoir: "Good evening",
  Bonjour: "Hello",
  bonne: "good",
  "bonne cuisine": "good food / cuisine",
  "bonne cuisine française": "good French food",
  "bonne idée": "good idea",
  bonnes: "good (fem plural)",
  bons: "good (masc plural)",
  bordeaux: "Bordeaux (city)",
  bouillabaisse: "bouillabaisse (fish stew)",
  brillaient: "were shining",
  bu: "drunk",
  buvez: "drink",
  buvons: "drink",
  "c'est": "it's",
  "c'est ben correct": "it's really good",
  "c'est capot": "it's crazy",
  "c'est chaud": "it's hot/difficult",
  "c'est chelou": "it's weird",
  "c'est cool": "it's cool",
  "c'est dingue": "it's crazy",
  "c'est écœurant": "it's disgusting/amazing",
  "c'est fort": "it's strong",
  "c'est génial": "it's awesome",
  "c'est gnama": "it's good",
  "c'est grave": "it's serious",
  "c'est le fun": "it's fun",
  "c'est malade": "it's sick",
  "c'est mortel": "it's awesome",
  "c'est nul": "it sucks",
  "c'est ouf": "it's crazy",
  "c'est poche": "it sucks",
  "C'est pour": "That's for / It's for",
  "C'est pour ça": "That's why",
  "c'est pour ça que": "that's why",
  "c'est quand": "it's when",
  "c'est quand je comprends": "it's when I understand",
  "c'est top": "it's the best",
  "c'est une": "it's a",
  "c'est une grande question": "it's a big question",
  "c'est une question": "it's a question",
  "c'est une question de méthode": "it's a question of method",
  "c'est vrai": "that's true / it's true",
  "c'est-à-dire": "that is to say",
  "c'était": "it was",
  "C'était": "It was",
  "c'était délicieux": "it was delicious",
  "C'était délicieux": "It was delicious",
  "C'était délicieux!": "It was delicious!",
  "C'était une": "It was a",
  "C'était une belle journée": "It was a beautiful day",
  "C'était une journée parfaite": "It was a perfect day",
  ça: "that/it",
  ca: "that/it",
  "ça prend": "it takes",
  "ça que": "that that / why",
  "ça que j'aime": "why I love",
  "ça va": "it's going / how are you",
  caen: "Caen - Historic Norman city",
  Caen: "Caen (historic Norman city)",
  café: "café / coffee",
  "Café de": "Café of",
  "Café de Flore": "Café de Flore (famous Parisian café)",
  "Café de Flore est": "Café de Flore is",
  "café ensemble": "coffee together",
  "café était": "café was",
  "café qui est": "café that is",
  "café.": "café.",
  cafés: "cafés",
  cafes: "cafés",
  campagne: "countryside",
  cannes: "Cannes (city)",
  Cannes: "Cannes (city)",
  capitale: "capital (city)",
  capot: "crazy (Quebec)",
  car: "because / for",
  "car j'ai": "because I have",
  carrefour: "intersection / crossroads",
  "carrefour de l'Odéon": "Odéon intersection",
  "car j'ai eu": "because I had",
  carafe: "carafe",
  carte: "card",
  cathédrale: "cathedral",
  cause: "cause",
  "cause du": "because of",
  "cause du temps": "because of time",
  ce: "this/that",
  "ce jour-là": "that day",
  "ce matin": "this morning",
  "ce moment": "this moment",
  "ce n'est pas": "it's not / that's not",
  "ce n'est pas la même chose": "it's not the same thing",
  "ce n'est pas la même chose qu'apprendre":
    "it's not the same thing as learning",
  "ce parc": "this park",
  "ce qu'on": "that which we / what we",
  "ce qu'on apprend": "what we learn",
  "ce que": "what / that which",
  "ce que nous voulons": "what we want",
  "ce que nous voulons faire": "what we want to do",
  célèbre: "famous",
  "célèbre à Paris": "famous in Paris",
  célèbres: "famous (plural)",
  celles: "those (fem)",
  "celles qu'on": "those that we",
  "celles qu'on ne": "those that we don't",
  certains: "some (people)",
  ces: "these/those",
  cet: "this (masc before vowel)",
  cette: "this",
  "cette rencontre": "this meeting",
  "Champs-Élysées": "Champs-Élysées (avenue)",
  "champs-élysées": "Champs-Élysées",
  change: "changes / change",
  changements: "changes",
  chaque: "each / every",
  "chaque année": "each year",
  chat: "cat",
  château: "castle / château",
  "château de Versailles": "Palace of Versailles",
  chats: "cats",
  chaud: "hot/difficult",
  chelou: "weird (slang)",
  cherche: "search / look for",
  cherchent: "look for (ils/elles)",
  chercher: "to search / to look for",
  chez: "at (someone's place)",
  "chez elle": "to her place / home",
  "chez moi": "to my place / home",
  "chez moi vers": "home around",
  chien: "dog",
  chiens: "dogs",
  chocolat: "chocolate",
  chose: "thing",
  choses: "things",
  cinéma: "cinema",
  "cinéma était près": "cinema was near",
  "cinéma.": "cinema.",
  cinq: "five",
  "cinq ans": "five years",
  citoyens: "citizens",
  Claude: "Claude (first name)",
  collective: "collective",
  combien: "how much/many",
  combine: "combines",
  commandé: "ordered",
  "commandé des": "ordered some",
  "commandé des sandwichs": "ordered sandwiches",
  comme: "as / since / like",
  "comme le coq au vin": "like coq au vin",
  "comme Lyon": "like Lyon",
  "comme Montmartre": "like Montmartre",
  "comme nous": "since we",
  "comme nous avions": "since we were",
  commence: "begins / starts",
  commencé: "started / begun",
  "commencé à parler": "started talking",
  comment: "how",
  "comment est": "how is",
  "comment est votre journée": "how is your day",
  "comment est-ce qu'on": "how do we",
  "comment est-ce qu'on apprend": "how do we learn",
  communiquent: "communicate (ils/elles)",
  comprenais: "understood / was understanding",
  comprend: "understands",
  "comprend mieux": "understands better",
  comprendre: "to understand",
  comprends: "understand (I/you)",
  "comprends bien": "understand well",
  "comprends bien maintenant": "understand well now",
  comprenez: "understand (you)",
  comprenons: "understand (we)",
  "comprenons bien": "understand well",
  compte: "counts / has",
  conclusion: "conclusion",
  connais: "know (I)",
  connaissance: "knowledge",
  connaître: "to know (people/places)",
  connectent: "connect (ils/elles)",
  content: "happy (masc)",
  "content que": "happy that / glad that",
  "content que tu sois": "glad you're",
  contente: "happy (fem)",
  contents: "happy (plural)",
  continué: "continued",
  continue: "continues",
  continuer: "to continue",
  continues: "continue (subjunctive, tu)",
  contributions: "contributions",
  conversation: "conversation",
  cool: "cool",
  coq: "rooster",
  côté: "side",
  "côté des fenêtres": "next to the windows",
  courage: "courage",
  cours: "class / course",
  coûte: "costs",
  coûtent: "cost",
  crédit: "credit",
  créé: "created",
  créent: "create (ils/elles)",
  croire: "to believe",
  "croire en": "to believe in",
  "croire en soi": "to believe in oneself",
  crois: "believe (I)",
  croissant: "croissant",
  croit: "believes",
  cuisine: "cuisine / food / kitchen",
  "cuisine française": "French cuisine",
  culinaires: "culinary",
  culture: "culture",
  culturelles: "cultural (fem plural)",
  d: "of/from",
  "d'abord": "first",
  "d'aider": "to help",
  "d'aller": "to go",
  "d'aller au": "to go to",
  "d'aller au café": "to go to the café",
  "d'apprendre": "of learning / to learn",
  "d'argent": "of money / (any) money",
  "d'aujourd'hui": "of today",
  "d'autres": "others",
  "d'enfants": "of children / (any) children",
  "d'être": "to be",
  "d'étudiants": "of students / some students",
  "d'habitants": "of inhabitants",
  "d'habitude": "usually",
  "D'habitude": "Usually",
  "d'important": "important",
  Dame: "Dame (Lady - part of Notre-Dame)",
  dans: "in",
  "dans la cuisine": "in the kitchen",
  "dans la mémoire": "in the memory",
  "dans le": "in the",
  "dans le café": "in the café",
  "dans le jardin": "in the garden",
  "dans le monde": "in the world",
  "dans une": "in a",
  "dans une autre": "in another",
  "dans une autre ville": "in another city",
  de: "of / from / some",
  "de bons restaurants": "good restaurants",
  "de ce": "about what / of this",
  "de ce que": "about what",
  "de ce que nous": "about what we",
  "de choses": "of things / things",
  "de dormir": "sleeping / to sleep",
  "de gens": "people / of people",
  "de gens -": "people -",
  "de l'université": "about university",
  "de l'université,": "about the university,",
  "de la": "some / of the",
  "de la bonne": "some good",
  "de la bonne cuisine": "good food",
  "de la bonne cuisine française": "good French food",
  "de la gare": "from the station / of the station",
  "de la Sorbonne": "about the Sorbonne / from the Sorbonne",
  "de ma": "of my / from my",
  "de manger": "to eat",
  "de manger ensemble": "to eat together",
  "de Marseille": "from Marseille",
  "de méthode": "of method",
  "de nos": "about our / of our",
  "de nos vies": "about our lives",
  "de Paris": "of Paris / in Paris",
  "de Paris!": "in Paris!",
  "de questions": "of questions / (any) questions",
  "de suite": "right away",
  "de tout": "of all / of everything",
  "de tout ce qu'on apprend": "of all that we learn",
  "de travail": "work / of work",
  "de Triomphe": "of Triumph",
  déchets: "waste / garbage",
  décidé: "decided",
  "décidé d'aller au": "decided to go to",
  "décidé de": "decided to",
  "décidé de manger": "decided to eat",
  découvrir: "to discover",
  dehors: "outside",
  déjà: "already",
  delà: "beyond (part of au-delà)",
  délicieux: "delicious",
  "délicieux!": "delicious!",
  demain: "tomorrow",
  demande: "asks / demands / requires",
  demandé: "asked",
  "demande du temps": "requires time",
  "demandé.": "asked.",
  demander: "to ask",
  "demander des questions": "to ask questions",
  dépêche: "hurry / hurries",
  dépêcher: "to hurry",
  dépend: "depends",
  déplacer: "to move around",
  depuis: "since / for (indicating duration)",
  "depuis cinq": "for five / since five",
  "depuis cinq ans": "for five years",
  "depuis six": "for six / since six",
  "depuis six mois": "for six months",
  dernier: "last",
  "dernier café": "last coffee",
  dernière: "last (feminine)",
  "dernière.": "last.",
  derrière: "behind",
  "derrière le cinéma": "behind the cinema",
  des: "some / of the",
  "des animaux": "animals / some animals",
  "des femmes": "women",
  "des fenêtres": "windows",
  "des heures": "hours",
  "des hommes": "men",
  "des idées": "ideas / some ideas",
  "des mots": "words",
  "des mots nouveaux": "new words",
  "des phrases": "phrases",
  "des questions": "questions / some questions",
  "des réponses": "answers",
  "des sandwichs": "sandwiches",
  "des tables": "tables / some tables",
  destination: "destination",
  destinations: "destinations",
  deux: "two",
  devant: "in front of / before",
  devenir: "to become",
  devez: "must",
  deviennent: "become (ils/elles)",
  devons: "must",
  devraient: "should",
  devrais: "should",
  devrait: "should",
  devriez: "should",
  devrions: "should",
  différemment: "differently",
  différente: "different (fem)",
  différentes: "different (fem plural)",
  difficile: "difficult",
  dingue: "crazy/wild",
  diplomates: "diplomats",
  dire: "to say / to tell",
  directions: "directions",
  dis: "say / tell (I/you)",
  discutent: "discuss (ils/elles)",
  dit: "says / tells",
  "dit qu'il": "said that he",
  "dit que": "said that",
  "dit.": "said.",
  dix: "ten",
  "dix minutes": "ten minutes",
  "dix minutes du": "ten minutes from",
  dois: "must",
  "dois me dépêcher": "must hurry",
  doit: "must",
  doivent: "must",
  donc: "so / therefore",
  donnent: "give (ils/elles)",
  dormir: "to sleep",
  "dormir,": "sleeping,",
  droite: "right",
  du: "of/from the (masc)",
  dû: "had to / due",
  "du café": "from the café / of coffee",
  "du Café": "from the Café",
  "du Café de": "from Café",
  "du Café de Flore": "from Café de Flore",
  "du célèbre": "of the famous",
  "du fromage": "cheese / some cheese",
  "du jardin": "of the garden / from the garden",
  "du lac": "of the lake / from the lake",
  "du Luxembourg": "of Luxembourg / Luxembourg's",
  "du Luxembourg près": "of Luxembourg near",
  "du Luxembourg,": "of Luxembourg,",
  "du monde": "of the world / from the world",
  "du pain": "bread / some bread",
  "du parc.": "of the park.",
  "dû partir": "had to leave",
  "dû partir vers": "had to leave around",
  "du temps": "time / of time",
  "du temps,": "of time,",
  dur: "hard",
  eau: "water",
  écœurant: "disgusting/amazing (Quebec)",
  école: "school",
  écoles: "schools",
  économique: "economic",
  économiques: "economic",
  économiser: "to save / conserve",
  écoute: "listen (command)",
  "écoute bien": "listen well",
  Éditeurs: "Les Éditeurs (café name)",
  éditeurs: "Les Éditeurs (café name)",
  écoutent: "listen (ils/elles)",
  éducatif: "educational",
  efforts: "efforts",
  également: "also / equally",
  Eiffel: "Eiffel",
  eiffel: "Eiffel",
  elle: "she / her",
  Elle: "She",
  "elle a bu": "she drank",
  "elle a dit": "she said",
  "elle a mangé": "she ate",
  "elle aime": "she likes/loves",
  "elle avait": "she had",
  "elle boit": "she drinks",
  "elle devrait": "she should",
  "Elle est": "She is",
  "elle est entrée": "she entered",
  "Elle est entrée dans": "She entered in",
  "elle est maintenant": "she's now",
  "elle est venue": "she came",
  "elle est venue à": "she came to",
  "elle était": "she was",
  "elle ferait": "she would do",
  "elle irait": "she would go",
  "elle mange": "she eats",
  "elle nous a vus": "she saw us",
  "Elle nous a vus": "She saw us",
  "elle pourrait": "she could",
  "elle voudrait": "she would like",
  "elle.": "her. / she.",
  elles: "they (fem)",
  "elles aiment": "they like/love",
  "elles avaient": "they had",
  "elles boivent": "they drink",
  "elles devraient": "they should",
  "elles étaient": "they were",
  "elles feraient": "they would do",
  "elles iraient": "they would go",
  "elles mangent": "they eat",
  "elles ont bu": "they drank",
  "elles ont mangé": "they ate",
  "elles pourraient": "they could",
  "elles voudraient": "they would like",
  embrassant: "embracing",
  en: "in / of it / some",
  "en apprentissage": "in learning / at learning",
  "en ce moment": "right now / at this moment",
  "en été": "in summer",
  "en Europe": "in Europe",
  "en face": "across / opposite",
  "en face de": "across from / opposite",
  "en face du": "across from the",
  "en face du jardin": "across from the garden",
  "en fait": "actually / in fact",
  "en français": "in French",
  "en France": "in France",
  "en ligne": "online",
  "en retard": "late",
  "en soi": "in oneself",
  "en train": "in the process / on the train",
  "en train de": "in the process of",
  encore: "still / again",
  "encore plus": "even more",
  encourage: "encourages",
  end: "end",
  énergie: "energy",
  enfant: "child",
  enfants: "children",
  enrichissent: "enrich (ils/elles)",
  ensemble: "together",
  "ensemble au": "together at",
  "ensemble au restaurant": "together at the restaurant",
  "ensemble pour": "together for",
  "ensemble pour l'après-midi": "together for the afternoon",
  "ensemble.": "together.",
  ensuite: "next / then",
  Ensuite: "Then / Next",
  "Ensuite,": "Then,",
  entier: "entire / whole",
  entre: "between",
  "entre les": "between the",
  "entre les idées": "between the ideas",
  entrée: "entered",
  "entrée dans": "entered in",
  "entrée dans le café": "entered in the café",
  entreprises: "companies",
  environnement: "environment",
  es: "are",
  espèces: "cash",
  espoir: "hope",
  essaies: "try (subjunctive, tu)",
  essayé: "tried",
  essayer: "to try",
  essentielles: "essential (fem plural)",
  est: "is",
  "est derrière": "is behind",
  "est derrière le": "is behind the",
  "est en face du": "is across from the",
  "est entrée": "entered",
  "est entrée dans le": "entered in the",
  "est le": "is the",
  "est le plus vieux": "is the oldest",
  "est le plus vieux restaurant": "is the oldest restaurant",
  "est maintenant": "is now",
  "est maintenant à": "is now in",
  "est très bon": "is very good",
  "est très bonne": "is very good",
  "est un voyage": "is a journey",
  "est venue": "came / has come",
  "est venue à notre": "came to our",
  "est votre journée": "is your day",
  "est-ce": "is it/this",
  "est-ce qu'on": "do we",
  et: "and",
  "et au-delà": "and beyond",
  "et de": "and about",
  "et de ce": "and about what",
  "et de ce que": "and about what",
  "et du": "and (some)",
  "et du café": "and coffee",
  "et elle": "and she",
  "et elle est venue": "and she came",
  "et je m'habille": "and I get dressed",
  "et je n'avais pas": "and I had no",
  "et moi": "and I",
  "et moi sommes": "and I stayed",
  "et on": "and we",
  "et on a commencé": "and we started",
  "et si": "and if",
  "et très célèbre": "and very famous",
  "et très célèbre à": "and very famous in",
  "et vous": "and you",
  étaient: "were",
  étais: "was",
  "étais fatigué": "was tired",
  était: "was",
  "était à": "was at / was to",
  "était assis": "was sitting",
  "était délicieux": "was delicious",
  "était excellent": "was excellent",
  "était excellent!": "was excellent!",
  "était notre": "was our",
  "était notre amie": "was our friend",
  "était près de": "was near",
  "était si": "was so",
  "était si beau": "was so nice",
  "était une": "was a",
  été: "summer / been",
  êtes: "are",
  "êtes en train de": "are in the process of",
  étiez: "were",
  étions: "were",
  étrangères: "foreign (fem plural)",
  étrangers: "foreign (masc plural)",
  être: "to be",
  "être dehors": "to be outside",
  "être ensemble": "to be together",
  "être ensemble pour": "to be together for",
  étude: "study (noun)",
  études: "studies",
  étudiant: "student",
  étudiants: "students",
  étudie: "study / studies",
  étudient: "study (ils/elles)",
  étudier: "to study",
  étudions: "study (we)",
  eu: "had (past participle of avoir)",
  "eu le": "had the",
  "eu le même": "had the same",
  "eu une": "had a",
  "eu une très belle": "had a very beautiful",
  europe: "Europe (continent)",
  Europe: "Europe (continent)",
  européennes: "European (fem plural)",
  eux: "them (masc)",
  évoluer: "to evolve",
  excellent: "excellent (masculine)",
  "excellent!": "excellent!",
  excellente: "excellent (feminine)",
  "excellente!": "excellent!",
  excusez: "excuse",
  "excusez-moi": "excuse me",
  existe: "exists",
  expériences: "experiences",
  "expériences culinaires": "culinary experiences",
  exportent: "export (ils/elles)",
  express: "espresso",
  face: "face",
  "face du": "opposite the / face of",
  facilement: "easily",
  faim: "hunger",
  "faim,": "hunger,",
  faire: "to do / to make",
  "faire.": "to do.",
  fais: "do / make (you)",
  "fais ici": "doing here",
  faisait: "was making / was (weather)",
  "faisait si beau": "was so nice",
  faisons: "do/make",
  fait: "does/makes",
  faites: "do/make",
  famille: "family",
  fatigue: "tiredness / fatigue",
  fatigué: "tired",
  "fatigué mais": "tired but",
  fatiguée: "tired (feminine)",
  faut: "is necessary / must",
  femme: "woman",
  femmes: "women",
  fenêtres: "windows",
  "fenêtres,": "windows,",
  feraient: "would do",
  ferais: "would do",
  ferait: "would do",
  feriez: "would do",
  ferions: "would do",
  fille: "girl",
  film: "film / movie",
  'film "Amélie"': 'film "Amélie"',
  'film "Amélie" - un': 'film "Amélie" - a',
  "film était": "film was",
  "film était excellent": "film was excellent",
  "film français": "French film",
  "film français!": "French film!",
  "film,": "film,",
  films: "films / movies",
  fin: "end",
  finalement: "finally",
  Finalement: "Finally",
  "Finalement,": "Finally,",
  "finalement,": "finally,",
  fini: "finished",
  finir: "to finish",
  Flore: "Flore (Flora)",
  "Flore est": "Flore is",
  "Flore.": "Flore.",
  fois: "time / occasion",
  fonctionne: "functions / works",
  font: "do/make",
  fort: "strong/intense",
  français: "French",
  francais: "French",
  "français!": "French!",
  française: "French (feminine)",
  françaises: "French (fem plural)",
  france: "France (country)",
  frère: "brother",
  frites: "fries",
  froid: "cold",
  fromage: "cheese",
  fruits: "fruits",
  garçon: "boy",
  garde: "keeps / maintains",
  gare: "train station",
  gâteau: "cake",
  gauche: "left",
  généralement: "generally",
  génération: "generation",
  génial: "awesome/great",
  gens: "people",
  "gens dans": "people in",
  "gens dans le": "people in the",
  gentil: "nice / kind",
  gentille: "kind (fem)",
  gentils: "nice / kind (plural)",
  glace: "ice cream",
  gnama: "good/tasty (Africa)",
  Gogh: "Gogh (surname)",
  gouvernement: "government",
  Grâce: "Thanks",
  grâce: "thanks",
  "grâce à": "thanks to",
  "Grâce à": "Thanks to",
  "grâce à cette": "thanks to this",
  "Grâce à cette": "Thanks to this",
  "Grâce à ma": "Thanks to my",
  "Grâce à ma sortie": "Thanks to my outing",
  grand: "big / large",
  "grand arbre": "big tree",
  grande: "big / large (fem)",
  grandes: "big (fem plural)",
  "grandes villes": "big cities",
  grands: "big/tall (masc plural)",
  gratuit: "free",
  gratuite: "free (fem)",
  grave: "serious/intense",
  h: "h (hour)",
  habille: "dress / dresses / get(s) dressed",
  habiller: "to dress",
  habitants: "inhabitants",
  habiter: "to live / to reside",
  habitude: "habit / usually",
  haricots: "beans",
  heure: "hour",
  "heure.": "hour.",
  heures: "hours",
  heureuse: "happy (feminine)",
  heureux: "happy (masculine)",
  "heureux.": "happy.",
  hier: "yesterday",
  historique: "historic",
  historiques: "historic (plural)",
  homme: "man",
  hommes: "men",
  homologues: "counterparts",
  honfleur: "Honfleur - Picturesque Norman port",
  Honfleur: "Honfleur (picturesque Norman port)",
  hui: "today",
  huit: "eight",
  hyper: "super/really",
  ici: "here",
  'ici!"': 'here!"',
  "ici?": "here?",
  'ici?"': 'here?"',
  idée: "idea",
  idées: "ideas",
  il: "he",
  Il: "He / It",
  "il a bu": "he drank",
  "il a dit": "he said",
  "il a mangé": "he ate",
  "il aime": "he likes/loves",
  "il avait": "he had",
  "il boit": "he drinks",
  "il devrait": "he should",
  "il était": "he was",
  "il était assis": "he was sitting",
  "il faisait": "it was (weather)",
  "il faut": "it is necessary / must",
  "il faut que": "it's necessary that / must",
  "il ferait": "he would do",
  "il irait": "he would go",
  "Il m'a": "He",
  "il m'a dit": "he told me",
  "Il m'a dit": "He told me",
  "Il m'a dit qu'il": "He told me that he",
  "il mange": "he eats",
  "il n'aimait pas": "he didn't like",
  "il pourrait": "he could",
  "il voudrait": "he would like",
  "il voulait": "he wanted",
  "il y avait beaucoup de gens": "there were many people",
  "Il y avait beaucoup de gens -": "There were many people -",
  "Il y avait le": "There was the",
  ils: "they (masc)",
  "ils aiment": "they like/love",
  "ils avaient": "they had",
  "ils boivent": "they drink",
  "ils devraient": "they should",
  "ils étaient": "they were",
  "ils feraient": "they would do",
  "ils iraient": "they would go",
  "ils mangent": "they eat",
  "ils ont bu": "they drank",
  "ils ont mangé": "they ate",
  "ils pourraient": "they could",
  "ils voudraient": "they would like",
  important: "important",
  importante: "important (fem)",
  importantes: "important (fem plural)",
  importants: "important (masc plural)",
  impressionnistes: "Impressionists",
  industrie: "industry",
  influence: "influences",
  informations: "information",
  innovation: "innovation",
  inoubliables: "unforgettable",
  inspirent: "inspire (ils/elles)",
  internationale: "international (fem)",
  internationalement: "internationally",
  internationales: "international (fem plural)",
  internet: "internet",
  iraient: "would go",
  irais: "would go",
  irait: "would go",
  iriez: "would go",
  irions: "would go",
  "j'achèterais": "I would buy",
  "j'adore": "I love / I adore",
  "j'ai": "I have",
  "j'ai besoin de": "I need",
  "j'ai bien appris": "I learned well",
  "j'ai bu": "I drank",
  "j'ai demandé": "I asked",
  "j'ai dit": "I said",
  "j'ai eu": "I had",
  "j'ai eu le": "I had the",
  "j'ai eu le même": "I had the same",
  "j'ai eu une": "I had a",
  "j'ai eu une très belle journée": "I had a very beautiful day",
  "j'ai mangé": "I ate",
  "j'ai parlé": "I spoke",
  "j'ai pensé": "I thought",
  "j'ai pensé:": "I thought:",
  "j'ai peur que": "I'm afraid that",
  "j'ai voulu": "I wanted",
  "j'ai voulu sortir": "I wanted to go out",
  "j'ai vu": "I saw",
  "j'ai vu mon": "I saw my",
  "j'aie": "I have (subjunctive)",
  "j'aime": "I love / I like",
  "J'aime beaucoup": "I really like",
  "j'aime beaucoup ce parc": "I really like this park",
  "j'aime bien": "I really like",
  "j'aime les": "I love the / I love",
  "j'aime les samedis": "I love Saturdays",
  "j'aime mes cours": "I like my classes",
  "j'aimerais": "I would like",
  "J'aimerais": "I would like",
  "j'aimerais que": "I would like (someone) to",
  "j'aurais": "I would have",
  "j'avais": "I had",
  "j'avais déjà": "I had already",
  "j'étais": "I was",
  "J'étais": "I was",
  "j'étais fatigué": "I was tired",
  "J'étais fatigué": "I was tired",
  "j'étudie": "I study",
  "j'étudie le français": "I study French",
  "j'habite": "I live",
  "j'irais": "I would go",
  jamais: "never",
  jardin: "garden",
  "Jardin des Tuileries": "Tuileries Garden",
  "Jardin du": "Garden of",
  "Jardin du Luxembourg": "Jardin du Luxembourg (famous Paris park)",
  jaune: "yellow",
  je: "I",
  Je: "I",
  "je bois": "I drink",
  "je comprenais": "I understood",
  "je comprenais car": "I understood because",
  "je comprends bien": "I understand well",
  "je devrais": "I should",
  "je dois me dépêcher": "I must hurry",
  "je ferais": "I would do",
  "je lui ai dit": "I told him",
  "Je lui ai dit que": "I told him that",
  "je m'appelle": "my name is",
  "je m'habille": "I get dressed",
  "je mange": "I eat",
  "je me dépêche": "I hurry",
  "je me lave": "I wash myself",
  "je me lave et": "I wash myself and",
  "je me levais": "I used to get up",
  "je me lève": "I get up",
  "je me prépare": "I get ready",
  "je me prépare pour": "I get ready for",
  "je me réveille": "I wake up",
  "je me souviens": "I remember",
  "je me souviens de tout": "I remember everything",
  "je me suis réveillé": "I woke up",
  "je n'avais pas de": "I had no",
  "je ne comprenais pas": "I didn't understand",
  "je ne me lève pas": "I don't get up",
  "je ne peux pas": "I can't",
  "je ne savais pas": "I didn't know",
  "Je ne savais pas que": "I didn't know that",
  "je paie": "I pay",
  "je pense": "I think",
  "je pense à ma journée": "I think about my day",
  "je pourrais": "I could",
  "je prends mon café": "I have my coffee",
  "je regrette que": "I regret that",
  "je rentre": "I return / I go back",
  "je révise": "I review",
  "je sais beaucoup": "I know a lot",
  "Je suis": "I am",
  "Je suis allé": "I went",
  "je suis allé près du": "I went near the",
  "je suis allé vers": "I went towards",
  "Je suis content": "I'm happy",
  "je suis content que": "I'm glad that",
  "Je suis content que tu sois": "I'm glad you're",
  "je suis contente": "I am happy (fem)",
  "je suis contente que": "I'm happy that (fem)",
  "je suis heureuse que": "I'm happy that (fem)",
  "je suis reconnaissante que": "I'm grateful that (fem)",
  "je suis rentré": "I went home",
  "je suis rentré chez": "I went home",
  "je t'aime": "I love you",
  "je vais apprendre": "I'm going to learn",
  "je vais dans": "I go into",
  "je vais manger": "I'm going to eat",
  "je vais manger avec": "I'm going to eat with",
  "je veux que": "I want (someone) to",
  "je voudrais": "I would like",
  "je voulais être": "I wanted to be",
  "Je voulais être": "I wanted to be",
  jeune: "young",
  jeunes: "young (plural)",
  jouer: "to play",
  "jouer un rôle": "to play a role",
  jour: "day",
  "jour-là": "that day",
  journée: "day",
  "journée avec": "day with",
  "journée parfaite": "perfect day",
  "journée parfaite à Paris": "perfect day in Paris",
  "journée.": "day.",
  journées: "days",
  "journées sont": "days are",
  jours: "days (plural of jour)",
  jus: "juice",
  juste: "just",
  "l'": "it",
  "l'agriculture": "agriculture / farming",
  "l'année": "the year",
  "l'année dernière": "last year",
  "l'apprentissage": "the learning / learning",
  "l'apprentissage est un voyage": "learning is a journey",
  "l'après": "the after",
  "L'après": "The after",
  "l'après-midi": "the afternoon",
  "L'après-midi": "In the afternoon / The afternoon",
  "L'après-midi,": "In the afternoon,",
  "l'Arc": "the Arc",
  "l'Arc de Triomphe": "the Arc de Triomphe",
  "l'autre": "the other",
  "l'avenir": "the future",
  "l'avons": "have her / have it",
  "l'avons pas": "have not",
  "l'avons pas vue": "haven't seen her",
  "l'eau": "water",
  "l'école": "school / the school",
  "l'économie": "the economy",
  "l'énergie": "energy / the energy",
  "l'environnement": "the environment",
  "l'espoir": "hope / the hope",
  "l'est": "the east",
  "l'étude": "the study",
  "l'europe": "Europe",
  "l'histoire": "history / the history",
  "l'industrie": "industry / the industry",
  "l'orange": "orange",
  "l'ouest": "the west",
  "l'Odéon": "Odéon (theater/area in Paris)",
  "l'odéon": "Odéon (theater/area in Paris)",
  "l'un": "the one",
  "l'un l'autre": "each other / one another",
  "l'université": "the university / university",
  "l'université,": "the university,",
  "l'université.": "the university.",
  la: "the / her / it",
  là: "there / here",
  "la banane": "banana",
  "la bière": "beer",
  "la bonne": "the good",
  "la bonne cuisine": "good food",
  "la cuisine": "the kitchen",
  "la France": "France",
  "la gare": "the station",
  "la glace": "ice cream",
  "la meilleure": "the best",
  "la même": "the same",
  "la même chose": "the same thing",
  "la méthode": "the method",
  "la pire": "the worst",
  "la pizza": "pizza",
  "la plus belle": "the most beautiful",
  "la pomme": "apple",
  "la pomme de terre": "potato",
  "la population": "the population",
  "la porte": "the door",
  "la preuve": "the proof",
  "la preuve que": "the proof that",
  "la révision est très bonne": "the review is very good",
  "la salade": "salad",
  "la Sorbonne": "the Sorbonne (famous Paris university)",
  "la sorbonne": "the Sorbonne",
  "la sortie": "the exit / outing",
  "la table": "the table",
  "la tomate": "tomato",
  "la Tour Eiffel": "The Eiffel Tower - 324m tall",
  "la viande": "meat",
  "là-bas": "over there",
  'là!"': 'there!"',
  lac: "lake",
  lait: "milk",
  langue: "language / tongue",
  langues: "languages",
  "langues étrangères": "foreign languages",
  lave: "wash / washes",
  laver: "to wash",
  le: "it/him",
  Le: "The",
  "le beurre": "butter",
  "le bœuf": "beef",
  "le café": "the coffee",
  "Le Café de Flore": "Café de Flore",
  "Le Café de Flore est": "Café de Flore is",
  "le café était": "the café was",
  "le café.": "the café.",
  "le chocolat": "chocolate",
  "le cinéma était": "the cinema was",
  "Le cinéma était": "The cinema was",
  "le cinéma.": "the cinema.",
  "le cours": "the class",
  "le faites": "do it",
  "le film": "the film",
  "Le film": "The film",
  'le film "Amélie"': 'the film "Amélie"',
  'le film "Amélie" -': 'the film "Amélie" -',
  "le film était": "the film was",
  "Le film était": "The film was",
  "Le film était excellent!": "The film was excellent!",
  "le film,": "the film,",
  "le français": "French / the French",
  "le fromage": "cheese",
  "le fun": "fun (Quebec)",
  "le gâteau": "cake",
  "le jardin": "the garden",
  "le Jardin des Tuileries": "the Tuileries Garden",
  "le jus": "juice",
  "le lait": "milk",
  "le long": "the length / along",
  "le long de": "along",
  "le meilleur": "the best",
  "le même": "the same",
  "le même problème": "the same problem",
  "le monde": "the world",
  "le pain": "bread",
  "le parc.": "the park.",
  "le peuple": "the people",
  "le pire": "the worst",
  "le plus": "the most",
  "le plus vieux": "the oldest",
  "le plus vieux restaurant": "the oldest restaurant",
  "le plus vieux restaurant de Paris": "the oldest restaurant in Paris",
  "le poisson": "fish",
  "le poivre": "pepper",
  "le porc": "pork",
  "le poulet": "chicken",
  "le prix": "the price",
  "Le Procope": "Le Procope (oldest restaurant in Paris)",
  "Le Procope est": "Le Procope is",
  "Le Procope est le": "Le Procope is the",
  "Le Procope qui": "Le Procope which",
  "le restaurant": "the restaurant",
  "le riz": "rice",
  "le samedi": "on Saturdays",
  "le sel": "salt",
  "le sucre": "sugar",
  "le temps": "time / the time",
  "le temps était": "the weather was",
  "le thé": "tea",
  "le train": "the train",
  "le vin": "wine",
  leçon: "lesson",
  leçons: "lessons",
  légumes: "vegetables",
  les: "the",
  "les animaux": "the animals",
  "les Champs-Élysées": "the Champs-Élysées",
  "les choses entre": "the things between",
  "les choses entre les idées": "the things between the ideas",
  "les cours": "the classes",
  "les étudiants": "the students",
  "les étudiants s'aident": "the students help each other",
  "les frites": "fries",
  "les fruits": "fruits",
  "les gens": "people (in general)",
  "les gens disent": "people say",
  "les gens pensent": "people think",
  "les haricots": "beans",
  "les idées": "the ideas",
  "les légumes": "vegetables",
  "les meilleures": "the best",
  "les meilleures journées": "the best days",
  "les meilleures journées sont": "the best days are",
  "les œufs": "eggs",
  "les pâtes": "pasta",
  "les personnes": "the people / persons",
  "les questions sont": "the questions are",
  "les questions sont essentielles": "questions are essential",
  "les questions sont très bonnes": "the questions are very good",
  "les restaurants": "the restaurants",
  "les samedis": "Saturdays",
  "les samedis à": "Saturdays in",
  "les samedis à Paris": "Saturdays in Paris",
  'les samedis à Paris!"': 'Saturdays in Paris!"',
  leur: "their",
  leurs: "their (plural)",
  levais: "was getting up",
  lève: "get up / gets up",
  lever: "to get up",
  lieux: "places / locations",
  ligne: "line / online",
  littérature: "literature",
  livre: "book",
  "livre de français": "French book",
  livres: "books",
  loin: "far",
  louvre: "Louvre (museum)",
  lui: "him / to him",
  "lui ai": "him have / told him",
  "lui ai dit": "told him",
  "lui ai dit que": "told him that",
  "lui et on": "him and we",
  lumières: "lights",
  Luxembourg: "Luxembourg",
  "Luxembourg,": "Luxembourg,",
  Lyon: "Lyon (major French city)",
  lyon: "Lyon (city)",
  "Lyon.": "Lyon.",
  "m'a": "me / to me",
  "m'a dit": "told me",
  "m'a dit qu'il": "told me that he",
  "m'aies": "me have (subjunctive)",
  "m'appelle": "call myself / my name is",
  "m'habille": "get dressed",
  ma: "my",
  "ma journée": "my day",
  "ma journée typique": "my typical day",
  "ma sortie": "my outing",
  "ma sortie au": "my outing to",
  "ma sortie au Jardin du Luxembourg": "my outing to Jardin du Luxembourg",
  madame: "madam / ma'am",
  magnifique: "magnificent / wonderful",
  magnifiques: "magnificent (plural)",
  main: "hand",
  maintenant: "now",
  "maintenant à": "now in",
  "maintenant dans": "now in",
  mais: "but",
  "mais très": "but very",
  "mais très heureux": "but very happy",
  "mais très heureux.": "but very happy.",
  maison: "house",
  maisons: "houses",
  mal: "badly/bad",
  malade: "sick/awesome (Quebec)",
  maman: "mom",
  mange: "eat",
  mangé: "eaten",
  "mangé de": "eaten some",
  "mangé de la": "eaten some",
  mangent: "eat",
  mangeons: "eat",
  manger: "to eat",
  "manger avec": "to eat with",
  "manger avec mes amis": "to eat with my friends",
  "manger ensemble": "to eat together",
  "manger ensemble au": "to eat together at",
  manges: "eat",
  mangez: "eat",
  mangions: "we were eating (nous form imparfait of manger)",
  "mangions,": "were eating,",
  manteau: "coat",
  marc: "Marc",
  marché: "walked / market",
  marcher: "to walk",
  marie: "Marie",
  Marie: "Marie (friend's name)",
  "Marie a": "Marie has",
  "Marie a dû": "Marie had to",
  "Marie a dû partir": "Marie had to leave",
  "Marie était": "Marie was",
  "Marie.": "Marie.",
  marseille: "Marseille (city)",
  matières: "subjects (school)",
  matin: "morning",
  mauvais: "bad",
  mauvaise: "bad (fem)",
  me: "me / myself",
  "me dépêche": "hurry",
  "me dis": "tell me",
  "me dit": "tells me / says to me",
  "me lave": "wash myself",
  "me lave et": "wash myself and",
  "me lave et je m'habille": "wash myself and get dressed",
  "me levais": "used to get up",
  "me lève": "get up (myself)",
  "me prépare": "get ready",
  "me prépare pour": "get ready for",
  "me réveille": "wake up (myself)",
  "me sens": "feel (I)",
  "me soutienne": "supports me (subjunctive)",
  "me soutiennent": "support me",
  "me souviens": "remember",
  "me souviens de": "remember (something)",
  "me souviens de tout": "remember everything",
  "me suis réveillé": "woke up",
  méditerranée: "Mediterranean",
  meilleur: "better/best (masc)",
  meilleure: "better/best (fem)",
  meilleures: "best (fem pl)",
  "meilleures journées": "best days",
  "meilleures journées sont": "best days are",
  même: "same / even",
  "même problème": "same problem",
  mémoire: "memory",
  "mémoire collective": "collective memory",
  mémorable: "memorable",
  mer: "sea",
  "mer Méditerranée": "Mediterranean Sea",
  merci: "thank you",
  mère: "mother",
  mes: "my",
  "mes amis": "my friends",
  "mes cours": "my classes",
  "mes idées": "my ideas",
  "mes pensées": "my thoughts",
  "mes rêves": "my dreams",
  met: "puts",
  méthode: "method",
  métro: "metro / subway",
  mets: "put (I/you)",
  mettre: "to put",
  Michel: "Michel (Michael - part of Mont-Saint-Michel)",
  michel: "Michel (michael - part of mont-saint-michel)",
  midi: "noon",
  mien: "mine",
  mieux: "better",
  millions: "millions",
  minutes: "minutes",
  "minutes du": "minutes from",
  "minutes du Café": "minutes from Café",
  moderne: "modern",
  moi: "me",
  "moi aussi": "me too",
  "moi sommes": "I stayed",
  "moi sommes restés": "I stayed",
  "moi vers": "me around",
  moins: "less",
  mois: "months",
  "mois parce": "months because",
  moment: "moment",
  mon: "my (masc)",
  "mon ami": "my friend",
  "mon café": "my coffee",
  "mon cours": "my class",
  "mon cours est": "my class is",
  "mon frère": "my brother",
  "mon livre": "my book",
  "mon livre de français": "my French book",
  "mon professeur": "my teacher",
  "mon professeur me dit": "my teacher tells me",
  monde: "world",
  mondiales: "global / world (fem plural)",
  Monet: "Monet (surname)",
  Mont: "Mont (Mount - part of Mont-Saint-Michel)",
  mont: "Mont (mount - part of mont-saint-michel)",
  "mont-saint-michel": "Mont-Saint-Michel (abbey)",
  "Mont-Saint-Michel": "Mont-Saint-Michel Abbey",
  montmartre: "Montmartre (district)",
  montrent: "show (ils/elles)",
  monuments: "monuments",
  mortel: "deadly/awesome",
  mot: "word",
  mots: "words",
  "mots nouveaux": "new words",
  musée: "museum",
  musique: "music",
  "n'ai": "don't have / haven't",
  "n'aimait": "didn't like",
  "n'aimait pas": "didn't like",
  "n'aimait pas son": "didn't like his",
  "n'apprends": "don't learn",
  "n'apprends pas": "don't learn / am not learning",
  "n'apprends pas vraiment": "am not really learning",
  "n'as": "don't have",
  "n'avais pas de": "had no",
  "n'est": "isn't / is not",
  nation: "nation",
  ne: "not / don't",
  "ne comprenais pas": "didn't understand",
  "ne comprenais pas tout": "didn't understand everything",
  "ne comprend pas": "doesn't understand",
  "ne comprends pas": "don't understand",
  "ne croit pas": "doesn't believe",
  "ne demande pas": "doesn't ask / don't ask",
  "ne demande pas de questions": "doesn't ask questions",
  "ne l'avons pas": "haven't / not have",
  "ne l'avons pas vue": "haven't seen her",
  "ne me lève pas": "don't get up",
  "ne me lève pas tout de suite": "don't get up right away",
  "ne pense": "don't think",
  "ne pense pas": "don't/doesn't think",
  "ne pense pas avoir": "don't think we'll have",
  "ne peux pas": "can't",
  "ne peux pas penser": "can't think",
  "ne pouvions pas": "could not",
  "ne savais": "didn't know",
  "ne savais pas": "didn't know",
  "ne savais pas que": "didn't know that",
  "ne sont pas": "aren't / are not",
  "ne sont pas bons": "aren't good",
  neuf: "nine",
  "neuf heures": "nine o'clock",
  nice: "Nice (city)",
  nom: "name",
  non: "no",
  nord: "north",
  normandie: "Normandy - Historic region of France",
  Normandie: "Normandy (historic region of France)",
  nos: "our",
  "nos vies": "our lives",
  notre: "our",
  Notre: "Notre (Our - part of Notre-Dame)",
  "notre amie": "our friend",
  "notre table": "our table",
  "notre-dame": "Notre-Dame (cathedral)",
  "Notre-Dame": "Notre-Dame Cathedral",
  nous: "us",
  Nous: "We",
  "nous a vus": "saw us",
  "nous a vus et": "saw us and",
  "nous aimons": "we like/love",
  "nous avions": "we had",
  "nous avions faim": "we were hungry",
  "Nous avons": "We have",
  "nous avons beaucoup aimé": "we really liked",
  "Nous avons beaucoup aimé": "We really liked",
  "nous avons bu": "we drank",
  "nous avons commandé": "we ordered",
  "Nous avons commandé": "We ordered",
  "nous avons décidé": "we decided",
  "nous avons décidé d'aller": "we decided to go",
  "nous avons décidé de": "we decided to",
  "nous avons décidé de manger": "we decided to eat",
  "nous avons mangé": "we ate",
  "nous avons mangé de": "we ate some",
  "nous avons mangé de la bonne cuisine française": "we ate good French food",
  "nous avons parlé": "we talked",
  "Nous avons parlé": "We talked",
  "nous avons parlé de": "we talked about",
  "Nous avons parlé pendant": "We talked for",
  "nous avons pris": "we had / took",
  "Nous avons pris un": "We had a",
  "nous avons pu": "we were able to",
  "nous avons pu être": "we were able to be",
  "nous avons pu être ensemble": "we were able to be together",
  "nous avons vu": "we saw",
  "nous avons vu Marie": "we saw Marie",
  "nous buvons": "we drink",
  "nous comprenons": "we understand",
  "nous devrions": "we should",
  "nous étions": "we were",
  "nous ferions": "we would do",
  "nous irions": "we would go",
  "nous mangeons": "we eat",
  "nous mangions": "we were eating",
  "nous ne l'avons pas vue": "we haven't seen her",
  "Nous ne l'avons pas vue": "We haven't seen her",
  "nous nous comprenons": "we understand each other",
  "nous nous comprenons bien": "we understand each other well",
  "nous pourrions": "we could",
  "nous sommes allés": "we went",
  "nous sommes allés au": "we went to",
  "nous voudrions": "we would like",
  "nous voulons": "we want",
  "nous voulons faire": "we want to do",
  "nous voulons faire.": "we want to do.",
  nouveau: "new",
  "nouveau travail": "new job",
  "nouveau travail à": "new job at",
  nouveaux: "new (masc plural)",
  "nouveaux artistes": "new artists",
  nouvelle: "new (fem)",
  nouvelles: "new (fem plural)",
  nuit: "night",
  nul: "sucks/lame",
  nulle: "no/none",
  œufs: "eggs",
  œuvres: "works (of art)",
  oh: "oh",
  on: "we / one",
  "on a": "we have / we",
  "on a commencé": "we started",
  "on a commencé à": "we started to",
  "on apprend": "we learn",
  "on apprend des mots": "we learn words",
  "on apprend des mots nouveaux": "we learn new words",
  "on cherche": "we search / we look for",
  "on commence": "we start / one starts",
  "on comprend": "we understand",
  "on dit": "we say / people say",
  "on doit": "we must / one must",
  "on est": "we are / one is",
  "on étudie": "we study",
  "on fait": "we do / we make",
  "on ne": "we don't / one doesn't",
  "on ne comprend pas": "we don't understand",
  "on ne croit pas": "we don't believe",
  "on ne demande pas": "we don't ask",
  "on ne pense pas": "we don't think",
  "on ne pense pas avoir": "we don't think we'll have",
  "on ne pense pas avoir.": "we don't think we'll have.",
  "on ne peut pas": "we can't / one cannot",
  "on ne va pas": "we're not going to",
  "on peut": "we can / one can",
  "on révise": "we review",
  "on s'amuse": "we have fun",
  "on s'amuse aussi": "we have fun too",
  "on sait": "we know",
  "on se parle": "we speak to each other",
  "on se parle en français": "we speak to each other in French",
  "on se pose": "we ask ourselves",
  "on se pose des questions": "we ask ourselves questions",
  "on se voit": "we see each other",
  "on se voit souvent": "we see each other often",
  "on trouve": "we find",
  "on va": "we go / we're going",
  "on veut": "we want",
  "on voit": "we see / one sees",
  ont: "have (ils/elles)",
  "ont bu": "drank",
  "ont créé": "have created",
  "ont mangé": "ate",
  orange: "orange",
  organisations: "organizations",
  ou: "or",
  où: "where",
  ouf: "crazy (slang)",
  oui: "yes",
  paie: "pay",
  paient: "pay",
  paies: "pay",
  pain: "bread",
  papa: "dad",
  parc: "park",
  "parc.": "park.",
  parce: "because",
  "parce qu'elle est": "because she is",
  "parce qu'il faisait": "because it was",
  "parce qu'il n'aimait": "because he didn't like",
  "parce que": "because",
  "parce que le": "because the",
  "parce que mon cours": "because my class",
  pardon: "excuse me",
  parents: "parents",
  parfaite: "perfect",
  "parfaite à": "perfect in",
  "parfaite à Paris.": "perfect in Paris.",
  Parfois: "Sometimes",
  parfois: "sometimes",
  "Parfois,": "Sometimes,",
  "parfois,": "sometimes,",
  paris: "Paris - Capital of France",
  Paris: "Paris (capital of France)",
  "Paris!": "Paris!",
  'Paris!"': 'Paris!"',
  "Paris.": "Paris.",
  parle: "speak (command)",
  parlé: "talked / spoken",
  "parle avec": "speak with",
  "parle avec tes amis": "speak with your friends",
  "parlé de": "talked about",
  "parlé de la": "talked about the",
  "parlé de la Sorbonne": "talked about the Sorbonne",
  "parlé pendant une": "talked for an",
  parlent: "speak",
  parler: "to speak",
  "parler français": "to speak French",
  "parler un peu": "to speak a little",
  "parler.": "to talk.",
  parles: "speak (you)",
  parlez: "speak",
  parlions: "were talking (nous, imparfait)",
  parlons: "speak",
  pars: "leave",
  part: "part/place",
  partent: "leave",
  partez: "leave",
  participe: "participates",
  partir: "to leave",
  "partir vers": "to leave around",
  partons: "leave",
  partout: "everywhere",
  "partout!": "everywhere!",
  pas: "not (part 2)",
  "pas avoir": "not have",
  "pas bons": "not good",
  "pas de travail": "no work",
  "pas que": "not that",
  "pas que vous": "that you",
  "pas son travail": "not his job",
  "pas tout": "not everything",
  "pas tout de suite": "not right away",
  "pas vue": "not seen",
  "pas vue depuis": "seen for / not seen since",
  pâtes: "pasta",
  patrimoine: "heritage",
  paul: "Paul",
  payer: "to pay",
  payez: "pay",
  payons: "pay",
  pays: "country",
  peintres: "painters",
  peintures: "paintings",
  pendant: "during / for",
  Pendant: "During / While",
  "pendant des heures": "for hours",
  "pendant le cours": "during class",
  "pendant que": "while",
  "Pendant que nous mangions": "While we were eating",
  "pendant quelques minutes": "for a few minutes",
  pensais: "was thinking",
  pense: "think (1st/3rd person singular present)",
  pensé: "thought (past participle of penser)",
  "pense à": "think about",
  "pense à ma journée": "think about my day",
  "pense en français": "think in French",
  "pense pas": "think not / don't think",
  "pense pas avoir": "think to have",
  "pense pas avoir.": "think to have.",
  "pensé:": "thought:",
  pensée: "thought",
  pensées: "thoughts",
  pensent: "think (they)",
  penser: "to think",
  "penser bien": "to think well",
  perdu: "lost",
  père: "father",
  permet: "allows / permits",
  personne: "person / nobody (with ne)",
  personnes: "people / persons",
  petit: "small (masc)",
  "petit café": "small café",
  petite: "small (fem)",
  "petite maison": "small house",
  petites: "small (fem plural)",
  petits: "small (masc plural)",
  peu: "little / few",
  "peu plus.": "more.",
  peuple: "people / population",
  peur: "fear",
  peut: "can",
  peuvent: "can",
  peux: "can",
  phrases: "phrases / sentences",
  pierre: "Pierre",
  Pierre: "Pierre (friend's name)",
  "Pierre et moi": "Pierre and I",
  "Pierre!": "Pierre!",
  "Pierre.": "Pierre.",
  pire: "worse/worst",
  pizza: "pizza",
  place: "square/place",
  plaisir: "pleasure",
  plaît: "pleases",
  plait: "pleases",
  planète: "planet",
  plats: "dishes",
  "plats traditionnels": "traditional dishes",
  plus: "more / most / plus",
  "plus belle": "most beautiful",
  "plus de": "more than",
  "plus tard": "later",
  "plus tôt": "earlier",
  "plus vieux": "older / oldest",
  "plus vieux restaurant": "oldest restaurant",
  "plus.": "more.",
  plusieurs: "several",
  poche: "sucks (Quebec)",
  poisson: "fish",
  poivre: "pepper",
  politiques: "political",
  pomme: "apple",
  "pomme de terre": "potato",
  pont: "bridge",
  populaire: "popular",
  populaires: "popular (plural)",
  population: "population",
  porc: "pork",
  porte: "door",
  pose: "asks / poses",
  "pose des questions": "asks questions",
  poulet: "chicken",
  pour: "for / to",
  "pour apprendre": "for learning / to learn",
  "pour ça": "for that / why",
  "pour ça que": "why / for that that",
  "pour l'après-midi": "for the afternoon",
  "pour l'université": "for university",
  "pour la Sorbonne": "for the Sorbonne",
  "pour la sorbonne": "for the Sorbonne",
  "pour que": "so that (someone can)",
  "pour rentrer": "to go back",
  "pour rentrer à": "to go back to",
  pourquoi: "why",
  pourraient: "could",
  pourrais: "could",
  pourrait: "could",
  pourriez: "could",
  pourrions: "could",
  pouvez: "can",
  pouvions: "could (imperfect)",
  pouvons: "can",
  préfèrent: "prefer (ils/elles)",
  première: "first (fem)",
  "première fois": "first time",
  prend: "takes / take",
  prendre: "to take",
  prends: "take / have",
  "prends mon café": "have my coffee",
  prépare: "prepare / get ready",
  préparer: "to prepare",
  près: "near",
  "près de": "near",
  "près de la": "near the",
  "près de la gare": "near the station",
  "près de ma maison": "near my house",
  "près de Notre-Dame": "near Notre-Dame",
  "près du": "near the",
  "près du célèbre": "near the famous",
  "près du lac": "near the lake",
  préserve: "preserves",
  preuve: "proof",
  primaire: "primary / elementary",
  pris: "taken / had",
  "pris un": "had a",
  "pris un dernier": "had one last",
  prix: "price",
  problème: "problem",
  "problème l'année": "problem last",
  Procope: "Procope",
  "Procope est": "Procope is",
  "Procope qui": "Procope which",
  produits: "products",
  professeur: "teacher / professor",
  profiter: "to enjoy / benefit from",
  protéger: "to protect",
  pu: "been able / could",
  "pu être": "been able to be",
  "pu être ensemble": "been able to be together",
  public: "public",
  publics: "public (masc plural)",
  puis: "then",
  "qu'apprendre": "than learning",
  "qu'elle": "that she",
  "qu'elle est": "that she is",
  "qu'elle est maintenant": "that she's now",
  "qu'est": "what is / that is",
  "qu'est-ce": "what is",
  "Qu'est-ce": "What",
  "Qu'est-ce qu'il y a": "What is there",
  "Qu'est-ce que tu fais ici": "What are you doing here",
  "qu'il": "that he / that it",
  "qu'il faisait": "that it was",
  "qu'il faisait si": "that it was so",
  "qu'il n'aimait pas": "that he didn't like",
  "qu'il voulait": "that he wanted",
  "qu'il voulait un": "that he wanted a",
  "qu'ils": "that they",
  "qu'ils ne sont pas": "that they're not",
  "qu'on": "that we / that one",
  "qu'on apprend": "that we/one learns",
  "qu'on ne": "that we don't",
  "qu'on ne pense pas": "that we don't think",
  "qu'on ne pense pas avoir": "that we don't think we'll have",
  "qu'on peut": "that we/one can",
  "qu'un": "that a / that one",
  quand: "when",
  "quand je": "when I",
  "quand je comprends": "when I understand",
  "quand je comprends une idée": "when I understand an idea",
  "quand on": "when we / when one",
  "quand on a": "when we have",
  "quand soudain": "when suddenly",
  quartier: "neighborhood / district",
  quartiers: "neighborhoods / districts",
  que: "than/that",
  "que j'aie": "that I have (subjunctive)",
  "que j'aie perdu": "that I lost/have lost",
  "que j'aime": "that I love",
  "que j'aime les": "that I love",
  "que je": "that I",
  "que je comprenais": "that I understood",
  "que le temps": "that the weather",
  "que nous": "that we",
  "que nous mangions": "that we were eating",
  "que nous voulons": "that we want",
  "que tu": "that you",
  "que tu sois": "that you are",
  "que vous": "that you",
  "que vous étiez": "that you were",
  Quelle: "What",
  "quelle surprise": "what a surprise",
  "Quelle surprise": "What a surprise",
  "Quelle surprise!": "What a surprise!",
  quel: "what / which",
  Quel: "What / Which",
  quelque: "some",
  "quelque chose": "something",
  quelques: "a few / some",
  "quelques minutes": "a few minutes",
  question: "question",
  questions: "questions",
  qui: "who / that / which",
  "qui est": "that/which is",
  "qui est derrière": "that is behind",
  "qui est derrière le": "which is behind the",
  "qui est derrière le cinéma": "that is behind the cinema",
  "qui est en face": "that is across",
  quoi: "you know (filler)",
  quotidienne: "daily",
  rais: "would (verb ending)",
  raison: "reason/right",
  rapidement: "rapidly",
  rapides: "fast (plural)",
  ratatouille: "ratatouille (dish)",
  réalité: "reality",
  reconnaissante: "grateful (fem)",
  reconnu: "recognized",
  recycler: "to recycle",
  regardais: "was looking at",
  regardent: "watch (ils/elles)",
  région: "region",
  regrette: "regret (I)",
  régulièrement: "regularly",
  relations: "relations",
  rencontre: "meeting / encounter",
  "rencontre,": "meeting,",
  rencontrer: "to meet",
  Renoir: "Renoir (surname)",
  renoncerais: "would give up",
  rentrant: "returning / going back",
  rentre: "return / go back",
  rentré: "went home",
  "rentré chez": "went home",
  "rentre chez moi": "return home",
  "rentré chez moi": "went home",
  rentrer: "to return / to go back home",
  "rentrer à": "to go back to",
  réponse: "answer",
  réponses: "answers",
  restaurant: "restaurant",
  Restaurant: "Restaurant",
  "restaurant de": "restaurant of / in",
  "restaurant de Paris": "restaurant in Paris",
  "Restaurant Le": "Restaurant Le",
  "Restaurant Le Procope": "Restaurant Le Procope",
  "restaurant qui est": "restaurant that is",
  "restaurant,": "restaurant,",
  restaurants: "restaurants",
  reste: "remains / stays",
  "reste également": "also remains",
  restent: "stay / remain (ils/elles)",
  rester: "to stay",
  restés: "stayed",
  "restés un": "stayed a",
  "restés un peu": "stayed a bit",
  retrouvé: "found again",
  réussi: "succeeded",
  réussisse: "succeeds (subjunctive)",
  réussissions: "succeed (subjunctive, nous)",
  rêve: "dream",
  réveille: "wake up / wakes up",
  réveillé: "woken up / awake",
  réveiller: "to wake up",
  rêver: "to dream",
  rêves: "dreams",
  révise: "review / reviews",
  réviser: "to review",
  révision: "review (noun)",
  revoir: "see again",
  riche: "rich",
  rien: "nothing",
  riz: "rice",
  rôle: "role",
  rouen: "Rouen - Norman capital city",
  Rouen: "Rouen (Norman capital city)",
  rouge: "red",
  rue: "street",
  s: "if/oneself",
  "s'aident": "help each other",
  "s'aider": "to help each other / oneself",
  "s'amuse": "has fun / have fun",
  "s'amuser": "to have fun",
  "s'appeler": "to be called / to call oneself",
  "s'habiller": "to get dressed",
  sa: "his/her (fem)",
  saches: "know (subjunctive, tu)",
  Saint: "Saint (Saint - part of Mont-Saint-Michel)",
  "Saint-Germain": "Saint-Germain-des-Prés (trendy Paris neighborhood)",
  "saint-germain": "Saint-Germain-des-Prés (trendy Paris neighborhood)",
  "à Saint-Germain": "to Saint-Germain-des-Prés",
  "à saint-germain": "to Saint-Germain-des-Prés",
  saint: "Saint (saint - part of mont-saint-michel)",
  sais: "know (I)",
  "sais beaucoup": "know a lot",
  "sais beaucoup de choses": "know many things",
  sait: "knows",
  salade: "salad",
  salut: "hi/bye",
  "Salut Pierre": "Hi Pierre",
  samedi: "Saturday",
  samedis: "Saturdays (plural)",
  "samedis à": "Saturdays in",
  "samedis à Paris": "Saturdays in Paris",
  sandwichs: "sandwiches",
  "sandwichs et": "sandwiches and",
  "sandwichs et du": "sandwiches and",
  sans: "without",
  saura: "will know",
  sauras: "will know (tu)",
  savais: "knew / was knowing",
  "savais pas": "didn't know",
  "savais pas que": "knew not that",
  savait: "knew / was knowing",
  savoir: "to know",
  scène: "scene / stage",
  sciences: "sciences",
  se: "himself / herself / themselves / each other",
  "se dépêcher": "to hurry",
  "se déplacer": "to move around",
  "se laver": "to wash oneself",
  "se lever": "to get up / to rise",
  "se parle": "speaks to each other",
  "se parle en français": "speak to each other in French",
  "se parlent": "speak to each other",
  "se pose": "asks oneself",
  "se pose des questions": "asks oneself questions",
  "se préparer": "to get ready / to prepare oneself",
  "se réveiller": "to wake up",
  "se sentir": "to feel",
  "se souvenir": "to remember",
  "se voit": "sees each other",
  "se voit souvent": "see each other often",
  secteurs: "sectors",
  seine: "Seine (river)",
  sel: "salt",
  semaine: "week",
  sens: "feel / sense",
  sept: "seven",
  "sept heures": "seven o'clock",
  serais: "would be",
  serveur: "waiter",
  services: "services",
  ses: "his/her (plural)",
  "ses livres": "his/her books",
  seulement: "only",
  si: "so / if",
  "si beau": "so nice",
  "si j'avais": "if I had",
  "si j'étais": "if I were",
  "si on": "if we / if one",
  "si on ne": "if we don't / if one doesn't",
  siècle: "century",
  sien: "his/hers",
  significatif: "significant",
  simplement: "simply",
  six: "six",
  "six mois": "six months",
  socrate: "Socrates",
  Socrate: "Socrates",
  "socrate pense": "Socrates thinks",
  "socrate pense que": "Socrates thinks that",
  soi: "oneself",
  soient: "are (subjunctive, ils/elles)",
  soir: "evening",
  soirée: "evening",
  sois: "are (subjunctive) / be",
  "sois là": "are here / be here",
  soit: "is / be (subjunctive)",
  soixante: "sixty",
  "soixante-huit": "sixty-eight",
  "soixante-huit millions": "sixty-eight million",
  soleil: "sun",
  sommes: "are",
  "sommes allés": "went / have gone",
  "sommes allés au": "went to",
  "sommes allés au cinéma": "went to the cinema",
  "sommes restés": "stayed / have stayed",
  "sommes restés un peu plus": "stayed a bit longer",
  son: "his / her",
  "son travail": "his job / work",
  sont: "are",
  "sont celles": "are those",
  "sont celles qu'on": "are those that we",
  "sont celles qu'on ne": "are those that we don't",
  "sont essentielles": "are essential",
  "sont meilleures": "are better",
  "sont pas": "are not",
  "sont très": "are very",
  "sont très bonnes": "are very good",
  sophie: "Sophie",
  Sorbonne: "Sorbonne",
  sorbonne: "Sorbonne",
  sortie: "exit / outing",
  "sortie au": "outing to",
  "sortie au Jardin": "outing to the Garden",
  sortir: "to go out",
  "sortir tôt": "to go out early",
  soudain: "suddenly",
  "soudain j'ai": "suddenly I",
  sous: "under / beneath",
  "sous un": "under a",
  "sous un grand": "under a big",
  soutiennent: "support (ils/elles)",
  souvenir: "to remember / memory",
  souvent: "often",
  souviens: "remember / remembers",
  soyons: "are (subjunctive, nous)",
  su: "known (past participle)",
  sucre: "sugar",
  sud: "south",
  suis: "am",
  "suis en train de": "am in the process of",
  "suis rentré": "went home / came back",
  "suis rentré chez moi": "went home",
  "suis réveillé": "woke up / am awake",
  suite: "immediately / continuation",
  super: "great / super",
  sur: "on",
  sûr: "sure / certain",
  "sur les Champs-Élysées": "on the Champs-Élysées",
  surprise: "surprise",
  'surprise!"': 'surprise!"',
  système: "system",
  ta: "your (fem, informal)",
  table: "table",
  "table.": "table.",
  tables: "tables",
  "tables,": "tables,",
  tard: "late",
  te: "you / yourself",
  technologie: "technology",
  téléphones: "phones",
  temps: "time/weather",
  "temps était": "weather was / time was",
  "temps,": "time,",
  tes: "your (plural, informal)",
  "tes amis": "your friends",
  "tes livres": "your books",
  tête: "head",
  thé: "tea",
  Thomas: "Thomas (French name)",
  thomas: "Thomas (French name)",
  tien: "yours",
  toi: "you",
  tomate: "tomato",
  ton: "your (masc, informal)",
  "ton manteau": "your coat",
  top: "top/best",
  tôt: "early",
  "tôt parce que": "early because",
  toujours: "always",
  Tour: "Tower",
  tour: "tower",
  "Tour Eiffel": "Eiffel Tower - Iconic landmark",
  touristes: "tourists",
  tous: "all (masc plural)",
  tout: "all / everything",
  "tout ce qu'on": "all that we",
  "tout ce qu'on apprend": "all that we learn",
  "tout de suite": "right away / immediately",
  "tout en": "while",
  "tout le monde": "everyone / everybody",
  toute: "all / whole (fem)",
  "toute l'Europe": "all of Europe",
  "toute la famille": "the whole family",
  "toute ma vie": "all my life / my whole life",
  toutes: "all (fem plural)",
  tradition: "tradition",
  traditionnels: "traditional (masc plural)",
  train: "train",
  trains: "trains",
  "trains rapides": "fast trains",
  transport: "transportation",
  "transport public": "public transportation",
  transports: "transportation (plural)",
  travail: "work",
  "travail à la": "job at the",
  "travail.": "job.",
  travaille: "works (il/elle)",
  travaillent: "work (ils/elles)",
  très: "very",
  "très belle": "very beautiful",
  "très belle journée": "very beautiful day",
  "très belle journée avec": "very beautiful day with",
  "très bien": "very well",
  "très bon": "very good",
  "très bon et": "very good and",
  "très bon film": "very good film",
  "très célèbre": "very famous",
  "très célèbre à Paris": "very famous in Paris",
  "très contente": "very happy",
  "très heureux": "very happy",
  "très populaire": "very popular",
  Triomphe: "Triumph",
  trois: "three",
  "trois heures": "three hours",
  "trois livres": "three books",
  trop: "too much/too",
  "trop tard": "too late",
  trouve: "find / finds",
  "trouve des réponses": "finds answers",
  trouver: "to find",
  tu: "you",
  "tu aimes": "you like/love",
  "tu as besoin de": "you need",
  "tu as bu": "you drank",
  "tu as mangé": "you ate",
  "tu avais": "you had",
  "tu bois": "you drink",
  "tu devrais": "you should",
  "tu étais": "you were",
  "tu fais": "you're doing / you do",
  "tu fais ici": "you're doing here",
  "tu ferais": "you would do",
  "tu irais": "you would go",
  "tu manges": "you eat",
  "tu me dis": "you tell me",
  "tu pourrais": "you could",
  "tu sois": "you are (subj)",
  "tu sois là": "you're here",
  "tu vas voir la Tour Eiffel": "you're going to see the Eiffel Tower",
  "tu voudrais": "you would like",
  typique: "typical",
  un: "a / one",
  "un banc sous": "a bench under",
  "un bon film": "a good film",
  "un café": "a coffee",
  "un croissant": "a croissant",
  "un dernier": "one last",
  "un dernier café": "one last coffee",
  "un express": "an espresso",
  "un grand arbre": "a big tree",
  "un nouveau": "a new",
  "un nouveau travail": "a new job",
  "un nouveau travail à": "a new job at",
  "un peu": "a bit / a little",
  "un peu plus": "a bit more",
  "un samedi": "a Saturday",
  "un très": "a very",
  "un très bon": "a very good",
  "un très bon film français": "a very good French film",
  "un voyage": "a journey",
  une: "a / one (fem)",
  "une autre": "another",
  "une autre ville": "another city",
  "une baguette": "a baguette",
  "une belle journée": "a beautiful day",
  "une bière": "a beer",
  "une grande question": "a big question",
  "une idée": "an idea",
  "une journée": "a day",
  "une journée parfaite": "a perfect day",
  "une journée parfaite à Paris": "a perfect day in Paris",
  "une personne": "a person",
  "une pizza": "a pizza",
  "une pomme": "an apple",
  "une question": "a question",
  "une réponse": "an answer",
  "une salade": "a salad",
  "une très": "a very",
  "une très belle": "a very beautiful",
  "une très belle journée": "a very beautiful day",
  unième: "-th (ordinal ending)",
  université: "university",
  "université,": "university,",
  "université.": "university.",
  universités: "universities",
  utiliser: "to use",
  va: "goes",
  "va avec": "goes with",
  "va faire": "are going to do",
  "va venir": "is going to come",
  vacances: "vacation",
  vachement: "really/very (slang)",
  vais: "go / am going",
  "vais apprendre": "going to learn",
  "vais dans": "go into",
  "vais dans la cuisine": "go into the kitchen",
  "vais manger": "going to eat",
  "vais prendre": "am going to take",
  valeurs: "values",
  vas: "go / are going",
  "vas prendre": "are going to take",
  "vas voir la Tour Eiffel": "are going to see the Eiffel Tower",
  vécu: "lived (past participle)",
  venez: "come",
  venir: "to come",
  venons: "come",
  venu: "come / came (past participle)",
  venue: "come",
  "venue à": "come to",
  "venue à notre table": "came to our table",
  vers: "towards",
  "vers 10h": "around 10pm",
  "vers 9h": "around 9pm",
  "vers l'est": "towards the east",
  "vers l'ouest": "towards the west",
  "vers la Seine": "towards the Seine",
  "vers le nord": "towards the north",
  "vers le sud": "towards the south",
  "vers lui et": "towards him and",
  Versailles: "Versailles",
  versailles: "Versailles",
  vert: "green",
  veulent: "want",
  veut: "wants",
  veux: "want",
  via: "via / through",
  viande: "meat",
  vie: "life",
  vieil: "old (masc before vowel)",
  vieille: "old (fem)",
  vieilles: "old (fem plural)",
  viennent: "come",
  viens: "come",
  vient: "comes",
  vies: "lives (plural of vie)",
  "vies,": "lives,",
  vieux: "old",
  "vieux restaurant": "old restaurant",
  "vieux restaurant de": "old restaurant in",
  ville: "city",
  "ville.": "city.",
  villes: "cities",
  vin: "wine",
  Vincent: "Vincent (first name)",
  vingt: "twenty",
  "vingt et unième siècle": "twenty-first century",
  visitent: "visit (ils/elles)",
  visiteurs: "visitors",
  vit: "lives (il/elle)",
  vivent: "live (ils/elles)",
  "vivent encore": "still live",
  voici: "here is / here are",
  "voici ma journée": "here is my day",
  voient: "see",
  voilà: "there is / that's",
  "voilà ma journée": "that's my day",
  voir: "to see",
  "voir la Tour Eiffel": "to see the Eiffel Tower",
  vois: "see",
  voit: "sees",
  voiture: "car",
  voitures: "cars",
  vont: "go",
  vos: "your (plural)",
  votre: "your (formal)",
  "votre journée": "your day",
  voudraient: "would like",
  voudrais: "would like",
  voudrait: "would like",
  voudriez: "would like",
  voudrions: "would like",
  voulais: "wanted",
  "voulais être": "wanted to be",
  "voulais être dehors": "wanted to be outside",
  voulait: "wanted",
  "voulait un nouveau": "wanted a new",
  voulez: "want",
  voulons: "want",
  "voulons faire": "want to do",
  "voulons faire.": "want to do.",
  voulu: "wanted",
  "voulu sortir": "wanted to go out",
  vous: "you (formal)",
  "vous aimez": "you like/love",
  "vous avez bu": "you drank",
  "vous avez mangé": "you ate",
  "vous aviez": "you had",
  "vous buvez": "you drink",
  "vous devriez": "you should",
  "vous êtes en train de": "you are in the process of",
  "vous étiez": "you were",
  "vous étiez ici": "you were here",
  "vous feriez": "you would do",
  "vous iriez": "you would go",
  "vous le faites": "you do it / you're doing it",
  "vous mangez": "you eat",
  "vous pourriez": "you could",
  "vous pouvez": "you can",
  "vous voudriez": "you would like",
  voyage: "journey / trip",
  voyagent: "travel (ils/elles)",
  voyagerais: "would travel",
  voyageurs: "travelers",
  voyons: "see",
  vrai: "true",
  vraiment: "really / truly",
  vu: "saw/seen",
  "vu mon ami": "saw my friend",
  vue: "seen",
  "vue depuis": "seen since",
  vus: "seen (past participle of voir)",
  "vus et": "seen and",
  week: "week",
  y: "there / to it",
  "y avait le": "there was the",
};
