/**
 * Nouns - Common nouns and food vocabulary
 */

// Common Nouns - Essential vocabulary from top 100 words
export const commonNouns = {
  livre: {
    french: "livre",
    english: "book",
    englishFull: "book",
    gender: "masculine",
    article: "un livre / le livre",
  },
  chat: {
    french: "chat",
    english: "cat (masculine)",
    englishFull: "cat (male)",
    gender: "masculine",
    article: "un chat / le chat",
  },
  chatte: {
    french: "chatte",
    english: "cat (feminine)",
    englishFull: "cat (female)",
    gender: "feminine",
    article: "une chatte / la chatte",
  },
  chien: {
    french: "chien",
    english: "dog (masculine)",
    englishFull: "dog (male)",
    gender: "masculine",
    article: "un chien / le chien",
  },
  chienne: {
    french: "chienne",
    english: "dog (feminine)",
    englishFull: "dog (female)",
    gender: "feminine",
    article: "une chienne / la chienne",
  },
  maison: {
    french: "maison",
    english: "house",
    englishFull: "house",
    gender: "feminine",
    article: "une maison / la maison",
  },
  voiture: {
    french: "voiture",
    english: "car",
    englishFull: "car",
    gender: "feminine",
    article: "une voiture / la voiture",
  },
  ami: {
    french: "ami",
    english: "friend (masculine)",
    englishFull: "friend (masculine)",
    gender: "masculine",
    article: "un ami / l'ami",
  },
  amie: {
    french: "amie",
    english: "friend (feminine)",
    englishFull: "friend (feminine)",
    gender: "feminine",
    article: "une amie / l'amie",
  },
  homme: {
    french: "homme",
    english: "man",
    englishFull: "man",
    gender: "masculine",
    article: "un homme / l'homme",
    note: "silent h",
  },
  femme: {
    french: "femme",
    english: "woman",
    englishFull: "woman",
    gender: "feminine",
    article: "une femme / la femme",
  },
  enfant: {
    french: "enfant",
    english: "child",
    englishFull: "child",
    gender: "masculine/feminine",
    article: "un enfant / une enfant",
    note: "same word both genders",
  },
  chose: {
    french: "chose",
    english: "thing",
    englishFull: "thing",
    gender: "feminine",
    article: "une chose / la chose",
  },
  jour: {
    french: "jour",
    english: "day",
    englishFull: "day",
    gender: "masculine",
    article: "un jour / le jour",
  },
  temps: {
    french: "temps",
    english: "time/weather",
    englishFull: "time/weather",
    gender: "masculine",
    article: "le temps",
    note: "can mean time OR weather",
  },
  vie: {
    french: "vie",
    english: "life",
    englishFull: "life",
    gender: "feminine",
    article: "la vie",
  },
  monde: {
    french: "monde",
    english: "world",
    englishFull: "world",
    gender: "masculine",
    article: "le monde",
    note: "tout le monde = everyone",
  },
  eau: {
    french: "eau",
    english: "water",
    englishFull: "water",
    gender: "feminine",
    article: "l'eau",
  },
  pain: {
    french: "pain",
    english: "bread",
    englishFull: "bread",
    gender: "masculine",
    article: "le pain",
  },
  argent: {
    french: "argent",
    english: "money",
    englishFull: "money",
    gender: "masculine",
    article: "l'argent",
    note: "also means silver",
  },
  travail: {
    french: "travail",
    english: "work",
    englishFull: "work",
    gender: "masculine",
    article: "le travail",
  },
  ville: {
    french: "ville",
    english: "city",
    englishFull: "city",
    gender: "feminine",
    article: "la ville",
  },
  place: {
    french: "place",
    english: "square/place",
    englishFull: "square/place",
    gender: "feminine",
    article: "la place",
  },
  rue: {
    french: "rue",
    english: "street",
    englishFull: "street",
    gender: "feminine",
    article: "la rue",
  },
  table: {
    french: "table",
    english: "table",
    englishFull: "table",
    gender: "feminine",
    article: "la table",
  },
  main: {
    french: "main",
    english: "hand",
    englishFull: "hand",
    gender: "feminine",
    article: "la main",
  },
  tete: {
    french: "tête",
    english: "head",
    englishFull: "head",
    gender: "feminine",
    article: "la tête",
  },
  nom: {
    french: "nom",
    english: "name",
    englishFull: "name",
    gender: "masculine",
    article: "le nom",
  },
  porte: {
    french: "porte",
    english: "door",
    englishFull: "door",
    gender: "feminine",
    article: "la porte",
  },
  personne: {
    french: "personne",
    english: "nobody/no one",
    englishFull: "nobody/no one",
    gender: "feminine",
    article: "personne",
    note: "often used with ne: je ne vois personne",
  },
  carteDeCredit: {
    french: "carte de crédit",
    english: "credit card",
    englishFull: "credit card",
    gender: "feminine",
    article: "la carte de crédit / une carte de crédit",
  },
  especes: {
    french: "espèces",
    english: "cash",
    englishFull: "cash",
    gender: "feminine",
    article: "les espèces / des espèces",
    note: "plural - payer en espèces",
  },
  carafeDeau: {
    french: "carafe d'eau",
    english: "carafe of water",
    englishFull: "carafe of water",
    gender: "feminine",
    article: "une carafe d'eau / la carafe d'eau",
  },
  addition: {
    french: "addition",
    english: "bill/check",
    englishFull: "the bill/check (at restaurant)",
    gender: "feminine",
    article: "l'addition",
    note: "used in restaurants",
  },
};

// Food & Drink Nouns - Essential everyday vocabulary
export const foodNouns = {
  // Drinks
  eau: {
    french: "l'eau",
    english: "water",
    gender: "feminine",
    article: "l'eau",
    note: "feminine, vowel start",
  },
  cafe: {
    french: "le café",
    english: "coffee",
    gender: "masculine",
    article: "le café / un café",
    note: "very common!",
  },
  express: {
    french: "un express",
    english: "espresso",
    gender: "masculine",
    article: "un express",
    note: "short strong coffee",
  },
  the: {
    french: "le thé",
    english: "tea",
    gender: "masculine",
    article: "le thé / un thé",
  },
  lait: {
    french: "le lait",
    english: "milk",
    gender: "masculine",
    article: "le lait / du lait",
  },
  vin: {
    french: "le vin",
    english: "wine",
    gender: "masculine",
    article: "le vin / du vin",
  },
  biere: {
    french: "la bière",
    english: "beer",
    gender: "feminine",
    article: "la bière / une bière",
  },
  jus: {
    french: "le jus",
    english: "juice",
    gender: "masculine",
    article: "le jus / du jus",
  },
  // Bread & Basics
  pain: {
    french: "le pain",
    english: "bread",
    gender: "masculine",
    article: "le pain / du pain",
    note: "essential!",
  },
  baguette: {
    french: "une baguette",
    english: "baguette",
    gender: "feminine",
    article: "une baguette / la baguette",
    note: "iconic French bread!",
  },
  croissant: {
    french: "un croissant",
    english: "croissant",
    gender: "masculine",
    article: "un croissant / le croissant",
    note: "classic breakfast!",
  },
  beurre: {
    french: "le beurre",
    english: "butter",
    gender: "masculine",
    article: "le beurre / du beurre",
  },
  fromage: {
    french: "le fromage",
    english: "cheese",
    gender: "masculine",
    article: "le fromage / du fromage",
  },
  pizza: {
    french: "la pizza",
    english: "pizza",
    gender: "feminine",
    article: "la pizza / une pizza",
  },
  sel: {
    french: "le sel",
    english: "salt",
    gender: "masculine",
    article: "le sel / du sel",
  },
  poivre: {
    french: "le poivre",
    english: "pepper",
    gender: "masculine",
    article: "le poivre / du poivre",
  },
  sucre: {
    french: "le sucre",
    english: "sugar",
    gender: "masculine",
    article: "le sucre / du sucre",
  },
  // Proteins
  viande: {
    french: "la viande",
    english: "meat",
    gender: "feminine",
    article: "la viande / de la viande",
  },
  poulet: {
    french: "le poulet",
    english: "chicken",
    gender: "masculine",
    article: "le poulet / du poulet",
  },
  poisson: {
    french: "le poisson",
    english: "fish",
    gender: "masculine",
    article: "le poisson / du poisson",
  },
  boeuf: {
    french: "le bœuf",
    english: "beef",
    gender: "masculine",
    article: "le bœuf / du bœuf",
  },
  porc: {
    french: "le porc",
    english: "pork",
    gender: "masculine",
    article: "le porc / du porc",
  },
  oeufs: {
    french: "les œufs",
    english: "eggs",
    gender: "masculine",
    article: "les œufs / des œufs",
    note: "plural",
  },
  // Vegetables
  legumes: {
    french: "les légumes",
    english: "vegetables",
    gender: "masculine",
    article: "les légumes / des légumes",
    note: "plural",
  },
  salade: {
    french: "la salade",
    english: "salad / lettuce",
    gender: "feminine",
    article: "la salade / une salade",
  },
  tomate: {
    french: "la tomate",
    english: "tomato",
    gender: "feminine",
    article: "la tomate / une tomate",
  },
  pommeDeTerre: {
    french: "la pomme de terre",
    english: "potato",
    gender: "feminine",
    article: "une pomme de terre",
    note: "literally 'apple of earth'",
  },
  frites: {
    french: "les frites",
    english: "fries",
    gender: "feminine",
    article: "les frites / des frites",
    note: "plural",
  },
  haricots: {
    french: "les haricots",
    english: "beans",
    gender: "masculine",
    article: "les haricots / des haricots",
    note: "plural",
  },
  // Fruits
  fruits: {
    french: "les fruits",
    english: "fruits",
    gender: "masculine",
    article: "les fruits / des fruits",
    note: "plural",
  },
  pomme: {
    french: "la pomme",
    english: "apple",
    gender: "feminine",
    article: "la pomme / une pomme",
  },
  banane: {
    french: "la banane",
    english: "banana",
    gender: "feminine",
    article: "la banane / une banane",
  },
  orange: {
    french: "l'orange",
    english: "orange",
    gender: "feminine",
    article: "l'orange / une orange",
  },
  // Carbs
  riz: {
    french: "le riz",
    english: "rice",
    gender: "masculine",
    article: "le riz / du riz",
  },
  pates: {
    french: "les pâtes",
    english: "pasta",
    gender: "feminine",
    article: "les pâtes / des pâtes",
    note: "plural",
  },
  // Desserts
  gateau: {
    french: "le gâteau",
    english: "cake",
    gender: "masculine",
    article: "le gâteau / un gâteau",
  },
  glace: {
    french: "la glace",
    english: "ice cream",
    gender: "feminine",
    article: "la glace / de la glace",
  },
  chocolat: {
    french: "le chocolat",
    english: "chocolate",
    gender: "masculine",
    article: "le chocolat / du chocolat",
  },
};

