/**
 * Possessive Adjectives and Pronouns - "my, your, his, her, mine, yours, etc."
 */

// Possessive adjectives - "my, your, his, her, our, their"
export const possessiveAdjectives = {
  mon: {
    french: "mon",
    english: "my (masculine)",
    englishFull: "my (masculine, like 'mon livre')",
    type: "possessive",
    owner: "je",
    gender: "masculine",
    number: "singular",
  },
  ma: {
    french: "ma",
    english: "my (feminine)",
    englishFull: "my (feminine, like 'ma maison')",
    type: "possessive",
    owner: "je",
    gender: "feminine",
    number: "singular",
  },
  mes: {
    french: "mes",
    english: "my (plural)",
    englishFull: "my (plural, like 'mes livres')",
    type: "possessive",
    owner: "je",
    number: "plural",
  },
  ton: {
    french: "ton",
    english: "your (masc, informal)",
    englishFull: "your (informal, masculine like 'ton chat')",
    type: "possessive",
    owner: "tu",
    gender: "masculine",
    number: "singular",
  },
  ta: {
    french: "ta",
    english: "your (fem, informal)",
    englishFull: "your (informal, feminine like 'ta voiture')",
    type: "possessive",
    owner: "tu",
    gender: "feminine",
    number: "singular",
  },
  tes: {
    french: "tes",
    english: "your (plural, informal)",
    englishFull: "your (informal, plural like 'tes amis')",
    type: "possessive",
    owner: "tu",
    number: "plural",
  },
  son: {
    french: "son",
    english: "his/her (masculine)",
    englishFull: "his/her (masculine, like 'son livre')",
    type: "possessive",
    owner: "il/elle",
    gender: "masculine",
    number: "singular",
  },
  sa: {
    french: "sa",
    english: "his/her (feminine)",
    englishFull: "his/her (feminine, like 'sa maison')",
    type: "possessive",
    owner: "il/elle",
    gender: "feminine",
    number: "singular",
  },
  ses: {
    french: "ses",
    english: "his/her (plural)",
    englishFull: "his/her (plural, like 'ses chats')",
    type: "possessive",
    owner: "il/elle",
    number: "plural",
  },
  notre: {
    french: "notre",
    english: "our (singular)",
    englishFull: "our (singular, like 'notre maison')",
    type: "possessive",
    owner: "nous",
    number: "singular",
  },
  nos: {
    french: "nos",
    english: "our (plural)",
    englishFull: "our (plural, like 'nos chats')",
    type: "possessive",
    owner: "nous",
    number: "plural",
  },
  votre: {
    french: "votre",
    english: "your (formal, singular)",
    englishFull: "your (formal, singular like 'votre livre')",
    type: "possessive",
    owner: "vous",
    number: "singular",
  },
  vos: {
    french: "vos",
    english: "your (formal, plural)",
    englishFull: "your (formal, plural like 'vos livres')",
    type: "possessive",
    owner: "vous",
    number: "plural",
  },
  leur: {
    french: "leur",
    english: "their (singular)",
    englishFull: "their (singular, like 'leur chat')",
    type: "possessive",
    owner: "ils/elles",
    number: "singular",
  },
  leurs: {
    french: "leurs",
    english: "their (plural)",
    englishFull: "their (plural, like 'leurs chats')",
    type: "possessive",
    owner: "ils/elles",
    number: "plural",
  },
};

// Possessive pronouns - "mine, yours, his, hers, ours, theirs"
export const possessivePronouns = {
  le_mien: {
    french: "le mien",
    english: "mine (masculine)",
    englishFull: "mine (masculine thing)",
    type: "possessive_pronoun",
    owner: "je",
    gender: "masculine",
  },
  la_mienne: {
    french: "la mienne",
    english: "mine (feminine)",
    englishFull: "mine (feminine thing)",
    type: "possessive_pronoun",
    owner: "je",
    gender: "feminine",
  },
  le_tien: {
    french: "le tien",
    english: "yours (masc, informal)",
    englishFull: "yours (informal, masculine thing)",
    type: "possessive_pronoun",
    owner: "tu",
    gender: "masculine",
  },
  la_tienne: {
    french: "la tienne",
    english: "yours (fem, informal)",
    englishFull: "yours (informal, feminine thing)",
    type: "possessive_pronoun",
    owner: "tu",
    gender: "feminine",
  },
  le_sien: {
    french: "le sien",
    english: "his/hers (masculine)",
    englishFull: "his/hers (masculine thing)",
    type: "possessive_pronoun",
    owner: "il/elle",
    gender: "masculine",
  },
  la_sienne: {
    french: "la sienne",
    english: "his/hers (feminine)",
    englishFull: "his/hers (feminine thing)",
    type: "possessive_pronoun",
    owner: "il/elle",
    gender: "feminine",
  },
  le_notre: {
    french: "le nôtre",
    english: "ours (masculine)",
    englishFull: "ours (masculine thing)",
    type: "possessive_pronoun",
    owner: "nous",
    gender: "masculine",
  },
  la_notre: {
    french: "la nôtre",
    english: "ours (feminine)",
    englishFull: "ours (feminine thing)",
    type: "possessive_pronoun",
    owner: "nous",
    gender: "feminine",
  },
  le_votre: {
    french: "le vôtre",
    english: "yours (formal, masculine)",
    englishFull: "yours (formal, masculine thing)",
    type: "possessive_pronoun",
    owner: "vous",
    gender: "masculine",
  },
  la_votre: {
    french: "la vôtre",
    english: "yours (formal, feminine)",
    englishFull: "yours (formal, feminine thing)",
    type: "possessive_pronoun",
    owner: "vous",
    gender: "feminine",
  },
  le_leur: {
    french: "le leur",
    english: "theirs (masculine)",
    englishFull: "theirs (masculine thing)",
    type: "possessive_pronoun",
    owner: "ils/elles",
    gender: "masculine",
  },
  la_leur: {
    french: "la leur",
    english: "theirs (feminine)",
    englishFull: "theirs (feminine thing)",
    type: "possessive_pronoun",
    owner: "ils/elles",
    gender: "feminine",
  },
};

