/**
 * Irregular Verbs - voir, boire, comprendre, savoir, connaître, croire
 */

// Verb voir (to see) conjugations
export const voirConjugations = {
  je: {
    pronoun: "je",
    conjugation: "vois",
    combined: "je vois",
    english: "I see",
    englishFull: "I see / I am seeing",
  },
  tu: {
    pronoun: "tu",
    conjugation: "vois",
    combined: "tu vois",
    english: "you see (informal)",
    englishFull: "you see / you are seeing (informal)",
  },
  il: {
    pronoun: "il",
    conjugation: "voit",
    combined: "il voit",
    english: "he sees",
    englishFull: "he sees / he is seeing",
  },
  elle: {
    pronoun: "elle",
    conjugation: "voit",
    combined: "elle voit",
    english: "she sees",
    englishFull: "she sees / she is seeing",
  },
  nous: {
    pronoun: "nous",
    conjugation: "voyons",
    combined: "nous voyons",
    english: "we see",
    englishFull: "we see / we are seeing",
  },
  vous: {
    pronoun: "vous",
    conjugation: "voyez",
    combined: "vous voyez",
    english: "you see (formal/plural)",
    englishFull: "you see / you are seeing (formal or plural)",
  },
  ils: {
    pronoun: "ils",
    conjugation: "voient",
    combined: "ils voient",
    english: "they see (masculine)",
    englishFull: "they see / they are seeing (masculine or mixed)",
  },
  elles: {
    pronoun: "elles",
    conjugation: "voient",
    combined: "elles voient",
    english: "they see (feminine)",
    englishFull: "they see / they are seeing (all feminine)",
  },
};

// Verb boire (to drink) conjugations - IRREGULAR
export const boireConjugations = {
  je: {
    pronoun: "je",
    conjugation: "bois",
    combined: "je bois",
    english: "I drink",
    englishFull: "I drink / I am drinking",
    note: "boi- stem",
  },
  tu: {
    pronoun: "tu",
    conjugation: "bois",
    combined: "tu bois",
    english: "you drink (informal)",
    englishFull: "you drink / you are drinking (informal)",
    note: "boi- stem",
  },
  il: {
    pronoun: "il",
    conjugation: "boit",
    combined: "il boit",
    english: "he drinks",
    englishFull: "he drinks / he is drinking",
    note: "boi- stem + t",
  },
  elle: {
    pronoun: "elle",
    conjugation: "boit",
    combined: "elle boit",
    english: "she drinks",
    englishFull: "she drinks / she is drinking",
    note: "boi- stem + t",
  },
  nous: {
    pronoun: "nous",
    conjugation: "buvons",
    combined: "nous buvons",
    english: "we drink",
    englishFull: "we drink / we are drinking",
    note: "STEM CHANGE to buv-",
  },
  vous: {
    pronoun: "vous",
    conjugation: "buvez",
    combined: "vous buvez",
    english: "you drink (formal/plural)",
    englishFull: "you drink / you are drinking (formal or plural)",
    note: "buv- stem",
  },
  ils: {
    pronoun: "ils",
    conjugation: "boivent",
    combined: "ils boivent",
    english: "they drink (masculine)",
    englishFull: "they drink / they are drinking (masculine or mixed)",
    note: "back to boi- stem + vent",
  },
  elles: {
    pronoun: "elles",
    conjugation: "boivent",
    combined: "elles boivent",
    english: "they drink (feminine)",
    englishFull: "they drink / they are drinking (all feminine)",
    note: "boi- stem + vent",
  },
};

// comprendre (to understand) - follows prendre pattern
export const comprendreConjugations = {
  je: {
    pronoun: "je",
    conjugation: "comprends",
    combined: "je comprends",
    english: "I understand",
    englishFull: "I understand",
    note: "same pattern as prendre",
  },
  tu: {
    pronoun: "tu",
    conjugation: "comprends",
    combined: "tu comprends",
    english: "you understand (informal)",
    englishFull: "you understand (informal)",
    note: "Tu comprends?",
  },
  il: {
    pronoun: "il",
    conjugation: "comprend",
    combined: "il comprend",
    english: "he understands",
    englishFull: "he understands",
    note: "no final -s or -t",
  },
  elle: {
    pronoun: "elle",
    conjugation: "comprend",
    combined: "elle comprend",
    english: "she understands",
    englishFull: "she understands",
    note: "same as il",
  },
  nous: {
    pronoun: "nous",
    conjugation: "comprenons",
    combined: "nous comprenons",
    english: "we understand",
    englishFull: "we understand",
    note: "add -ons",
  },
  vous: {
    pronoun: "vous",
    conjugation: "comprenez",
    combined: "vous comprenez",
    english: "you understand (formal/plural)",
    englishFull: "you understand (formal or plural)",
    note: "polite form",
  },
  ils: {
    pronoun: "ils",
    conjugation: "comprennent",
    combined: "ils comprennent",
    english: "they understand (masculine)",
    englishFull: "they understand (masculine or mixed)",
    note: "double n, silent -ent",
  },
  elles: {
    pronoun: "elles",
    conjugation: "comprennent",
    combined: "elles comprennent",
    english: "they understand (feminine)",
    englishFull: "they understand (all feminine)",
    note: "double n, silent -ent",
  },
};

// savoir (to know facts/skills) - irregular, rank 21!
export const savoirConjugations = {
  je: {
    pronoun: "je",
    conjugation: "sais",
    combined: "je sais",
    english: "I know",
    englishFull: "I know",
    note: "⭐ je ne sais pas = most common phrase!",
  },
  tu: {
    pronoun: "tu",
    conjugation: "sais",
    combined: "tu sais",
    english: "you know (informal)",
    englishFull: "you know (informal)",
    note: "Tu sais?",
  },
  il: {
    pronoun: "il",
    conjugation: "sait",
    combined: "il sait",
    english: "he knows",
    englishFull: "he knows",
    note: "silent -t",
  },
  elle: {
    pronoun: "elle",
    conjugation: "sait",
    combined: "elle sait",
    english: "she knows",
    englishFull: "she knows",
    note: "silent -t",
  },
  nous: {
    pronoun: "nous",
    conjugation: "savons",
    combined: "nous savons",
    english: "we know",
    englishFull: "we know",
    note: "pronounced 'sa-von'",
  },
  vous: {
    pronoun: "vous",
    conjugation: "savez",
    combined: "vous savez",
    english: "you know (formal/plural)",
    englishFull: "you know (formal or plural)",
    note: "pronounced 'sa-vay'",
  },
  ils: {
    pronoun: "ils",
    conjugation: "savent",
    combined: "ils savent",
    english: "they know (masculine)",
    englishFull: "they know (masculine or mixed)",
    note: "silent -ent",
  },
  elles: {
    pronoun: "elles",
    conjugation: "savent",
    combined: "elles savent",
    english: "they know (feminine)",
    englishFull: "they know (all feminine)",
    note: "silent -ent",
  },
};

// connaître (to know people/places) - irregular, rank 62
export const connaitreConjugations = {
  je: {
    pronoun: "je",
    conjugation: "connais",
    combined: "je connais",
    english: "I know",
    englishFull: "I know (people/places)",
    note: "for people and places only",
  },
  tu: {
    pronoun: "tu",
    conjugation: "connais",
    combined: "tu connais",
    english: "you know (informal)",
    englishFull: "you know (informal)",
    note: "Tu connais Marie?",
  },
  il: {
    pronoun: "il",
    conjugation: "connaît",
    combined: "il connaît",
    english: "he knows",
    englishFull: "he knows",
    note: "⚠️ circumflex accent î",
  },
  elle: {
    pronoun: "elle",
    conjugation: "connaît",
    combined: "elle connaît",
    english: "she knows",
    englishFull: "she knows",
    note: "circumflex accent î",
  },
  nous: {
    pronoun: "nous",
    conjugation: "connaissons",
    combined: "nous connaissons",
    english: "we know",
    englishFull: "we know",
    note: "double -ss-",
  },
  vous: {
    pronoun: "vous",
    conjugation: "connaissez",
    combined: "vous connaissez",
    english: "you know (formal/plural)",
    englishFull: "you know (formal or plural)",
    note: "double -ss-",
  },
  ils: {
    pronoun: "ils",
    conjugation: "connaissent",
    combined: "ils connaissent",
    english: "they know (masculine)",
    englishFull: "they know (masculine or mixed)",
    note: "double -ss-, silent -ent",
  },
  elles: {
    pronoun: "elles",
    conjugation: "connaissent",
    combined: "elles connaissent",
    english: "they know (feminine)",
    englishFull: "they know (all feminine)",
    note: "double -ss-, silent -ent",
  },
};

// croire (to believe) - irregular, rank 60
export const croireConjugations = {
  je: {
    pronoun: "je",
    conjugation: "crois",
    combined: "je crois",
    english: "I believe / I think",
    englishFull: "I believe / I think",
    note: "pronounced 'krwa'",
  },
  tu: {
    pronoun: "tu",
    conjugation: "crois",
    combined: "tu crois",
    english: "you believe (informal)",
    englishFull: "you believe / you think (informal)",
    note: "Tu crois?",
  },
  il: {
    pronoun: "il",
    conjugation: "croit",
    combined: "il croit",
    english: "he believes",
    englishFull: "he believes / he thinks",
    note: "silent -t",
  },
  elle: {
    pronoun: "elle",
    conjugation: "croit",
    combined: "elle croit",
    english: "she believes",
    englishFull: "she believes / she thinks",
    note: "silent -t",
  },
  nous: {
    pronoun: "nous",
    conjugation: "croyons",
    combined: "nous croyons",
    english: "we believe",
    englishFull: "we believe / we think",
    note: "y sound - 'krwa-yon'",
  },
  vous: {
    pronoun: "vous",
    conjugation: "croyez",
    combined: "vous croyez",
    english: "you believe (formal/plural)",
    englishFull: "you believe / you think (formal or plural)",
    note: "y sound - 'krwa-yay'",
  },
  ils: {
    pronoun: "ils",
    conjugation: "croient",
    combined: "ils croient",
    english: "they believe (masculine)",
    englishFull: "they believe / they think (masculine or mixed)",
    note: "silent -ent",
  },
  elles: {
    pronoun: "elles",
    conjugation: "croient",
    combined: "elles croient",
    english: "they believe (feminine)",
    englishFull: "they believe / they think (all feminine)",
    note: "silent -ent",
  },
};

