/**
 * Past Tense (Passé Composé) Conjugations
 */

// Verb manger - Passé Composé (Past Tense)
export const mangerPasseComposeConjugations = {
  je: {
    pronoun: "je",
    auxiliary: "ai",
    pastParticiple: "mangé",
    combined: "j'ai mangé",
    english: "I ate / I have eaten",
    englishFull: "I ate / I have eaten",
    note: "passé composé - regular -ER past participle",
  },
  tu: {
    pronoun: "tu",
    auxiliary: "as",
    pastParticiple: "mangé",
    combined: "tu as mangé",
    english: "you ate (informal)",
    englishFull: "you ate / you have eaten (informal)",
    note: "passé composé",
  },
  il: {
    pronoun: "il",
    auxiliary: "a",
    pastParticiple: "mangé",
    combined: "il a mangé",
    english: "he ate",
    englishFull: "he ate / he has eaten",
    note: "passé composé",
  },
  elle: {
    pronoun: "elle",
    auxiliary: "a",
    pastParticiple: "mangé",
    combined: "elle a mangé",
    english: "she ate",
    englishFull: "she ate / she has eaten",
    note: "passé composé",
  },
  nous: {
    pronoun: "nous",
    auxiliary: "avons",
    pastParticiple: "mangé",
    combined: "nous avons mangé",
    english: "we ate",
    englishFull: "we ate / we have eaten",
    note: "passé composé",
  },
  vous: {
    pronoun: "vous",
    auxiliary: "avez",
    pastParticiple: "mangé",
    combined: "vous avez mangé",
    english: "you ate (formal/plural)",
    englishFull: "you ate / you have eaten (formal or plural)",
    note: "passé composé",
  },
  ils: {
    pronoun: "ils",
    auxiliary: "ont",
    pastParticiple: "mangé",
    combined: "ils ont mangé",
    english: "they ate (masculine)",
    englishFull: "they ate / they have eaten (masculine or mixed)",
    note: "passé composé",
  },
  elles: {
    pronoun: "elles",
    auxiliary: "ont",
    pastParticiple: "mangé",
    combined: "elles ont mangé",
    english: "they ate (feminine)",
    englishFull: "they ate / they have eaten (all feminine)",
    note: "passé composé",
  },
};

// Verb boire - Passé Composé (Past Tense) - IRREGULAR
export const boirePasseComposeConjugations = {
  je: {
    pronoun: "je",
    auxiliary: "ai",
    pastParticiple: "bu",
    combined: "j'ai bu",
    english: "I drank / I have drunk",
    englishFull: "I drank / I have drunk",
    note: "passé composé - IRREGULAR past participle: bu",
  },
  tu: {
    pronoun: "tu",
    auxiliary: "as",
    pastParticiple: "bu",
    combined: "tu as bu",
    english: "you drank (informal)",
    englishFull: "you drank / you have drunk (informal)",
    note: "passé composé",
  },
  il: {
    pronoun: "il",
    auxiliary: "a",
    pastParticiple: "bu",
    combined: "il a bu",
    english: "he drank",
    englishFull: "he drank / he has drunk",
    note: "passé composé",
  },
  elle: {
    pronoun: "elle",
    auxiliary: "a",
    pastParticiple: "bu",
    combined: "elle a bu",
    english: "she drank",
    englishFull: "she drank / she has drunk",
    note: "passé composé",
  },
  nous: {
    pronoun: "nous",
    auxiliary: "avons",
    pastParticiple: "bu",
    combined: "nous avons bu",
    english: "we drank",
    englishFull: "we drank / we have drunk",
    note: "passé composé",
  },
  vous: {
    pronoun: "vous",
    auxiliary: "avez",
    pastParticiple: "bu",
    combined: "vous avez bu",
    english: "you drank (formal/plural)",
    englishFull: "you drank / you have drunk (formal or plural)",
    note: "passé composé",
  },
  ils: {
    pronoun: "ils",
    auxiliary: "ont",
    pastParticiple: "bu",
    combined: "ils ont bu",
    english: "they drank (masculine)",
    englishFull: "they drank / they have drunk (masculine or mixed)",
    note: "passé composé",
  },
  elles: {
    pronoun: "elles",
    auxiliary: "ont",
    pastParticiple: "bu",
    combined: "elles ont bu",
    english: "they drank (feminine)",
    englishFull: "they drank / they have drunk (all feminine)",
    note: "passé composé",
  },
};

